/**
 * Hand-written runtime helpers — NOT generated by @hey-api/openapi-ts.
 *
 * The generator writes every `*.gen.ts` file and `src/index.ts`. It runs with
 * `clean: false` (see generate.mjs) so this module is left untouched on each
 * `pnpm generate`. It is published under the
 * `@diogopms/invoice-express-js/interceptors` subpath export.
 *
 * Two concerns are covered, both built on capabilities the underlying fetch
 * client already exposes:
 *
 *   1. Logging interceptors — middleware on the shared `client` that logs every
 *      request, response and error (`client.interceptors.*`).
 *   2. Fetch decorators — small, composable wrappers around `fetch` so you can
 *      inject logging, timeouts, retries or swap in a custom HTTP client via
 *      `client.setConfig({ fetch })`.
 */

import type { Client, ResolvedRequestOptions } from "./client/index.js";

// ---------------------------------------------------------------------------
// Logger
// ---------------------------------------------------------------------------

/**
 * Minimal structured logger. Compatible with `console` and with most logging
 * libraries (pino, winston, bunyan) once adapted. `debug` is optional so a bare
 * `{ info, warn, error }` object is enough.
 */
export interface Logger {
  debug?(message: string, meta?: Record<string, unknown>): void;
  info(message: string, meta?: Record<string, unknown>): void;
  warn(message: string, meta?: Record<string, unknown>): void;
  error(message: string, meta?: Record<string, unknown>): void;
}

/** Default logger that writes to the global `console`. */
export const consoleLogger: Logger = {
  debug: (message, meta) => console.debug(message, meta ?? ""),
  info: (message, meta) => console.info(message, meta ?? ""),
  warn: (message, meta) => console.warn(message, meta ?? ""),
  error: (message, meta) => console.error(message, meta ?? ""),
};

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Extract a string URL from any `fetch` first-argument shape. */
function requestUrl(input: RequestInfo | URL): string {
  if (typeof input === "string") return input;
  if (input instanceof URL) return input.href;
  return input.url;
}

/**
 * Replace the values of sensitive query params (e.g. `api_key`, which the
 * InvoiceXpress API carries in the query string) with `***` so they never reach
 * your logs. Invalid URLs are returned untouched.
 */
function redactUrl(url: string, params: readonly string[]): string {
  if (params.length === 0) return url;
  try {
    const parsed = new URL(url);
    let changed = false;
    for (const name of params) {
      if (parsed.searchParams.has(name)) {
        parsed.searchParams.set(name, "***");
        changed = true;
      }
    }
    return changed ? parsed.toString() : url;
  } catch {
    return url;
  }
}

/** Monotonic-ish millisecond timestamp used for request timing. */
function now(): number {
  return typeof performance !== "undefined" && performance.now
    ? performance.now()
    : Date.now();
}

// ---------------------------------------------------------------------------
// Logging interceptors
// ---------------------------------------------------------------------------

export interface LoggingOptions {
  /** Logger to write to. Defaults to {@link consoleLogger}. */
  logger?: Logger;
  /**
   * Level used for the normal request/response lines. Failed responses
   * (`!response.ok`) and thrown errors are always logged at `warn`/`error`.
   *
   * @default "info"
   */
  level?: "debug" | "info";
  /**
   * Query-string parameter names to redact from logged URLs.
   *
   * @default ["api_key"]
   */
  redactQueryParams?: readonly string[];
}

export interface LoggingInterceptors {
  onRequest: (request: Request, options: ResolvedRequestOptions) => Request;
  onResponse: (
    response: Response,
    request: Request,
    options: ResolvedRequestOptions,
  ) => Response;
  onError: (
    error: unknown,
    response: Response | undefined,
    request: Request | undefined,
    options: ResolvedRequestOptions,
  ) => unknown;
}

/**
 * Build a set of request/response/error interceptors that log each call,
 * including the elapsed time. Pass them to the shared client yourself, or use
 * {@link attachLogging} to register all three at once.
 *
 * @example
 * const { onRequest, onResponse, onError } = createLoggingInterceptors();
 * client.interceptors.request.use(onRequest);
 * client.interceptors.response.use(onResponse);
 * client.interceptors.error.use(onError);
 */
export function createLoggingInterceptors(
  options: LoggingOptions = {},
): LoggingInterceptors {
  const logger = options.logger ?? consoleLogger;
  const level = options.level ?? "info";
  const redact = options.redactQueryParams ?? ["api_key"];
  const log = level === "debug" ? (logger.debug ?? logger.info) : logger.info;

  // Timing is keyed on the Request object, which the client passes unchanged
  // from the request interceptor through to the response/error interceptors.
  const startedAt = new WeakMap<Request, number>();

  const elapsed = (request: Request | undefined): number | undefined => {
    if (!request) return undefined;
    const start = startedAt.get(request);
    return start === undefined ? undefined : Math.round(now() - start);
  };

  return {
    onRequest: (request) => {
      startedAt.set(request, now());
      log("→ request", {
        method: request.method,
        url: redactUrl(request.url, redact),
      });
      return request;
    },
    onResponse: (response, request) => {
      const meta = {
        method: request.method,
        url: redactUrl(request.url, redact),
        status: response.status,
        durationMs: elapsed(request),
      };
      if (response.ok) {
        log("← response", meta);
      } else {
        logger.warn("← response (error status)", meta);
      }
      return response;
    },
    onError: (error, response, request) => {
      logger.error("✗ request failed", {
        method: request?.method,
        url: request ? redactUrl(request.url, redact) : undefined,
        status: response?.status,
        durationMs: elapsed(request),
        error: error instanceof Error ? error.message : error,
      });
      return error;
    },
  };
}

/**
 * Register logging interceptors on a client in one call.
 *
 * @returns a disposer that removes the interceptors again (handy for tests or
 *   for swapping logging configuration at runtime).
 *
 * @example
 * import { client } from "@diogopms/invoice-express-js";
 * import { attachLogging } from "@diogopms/invoice-express-js/interceptors";
 *
 * const detach = attachLogging(client, { redactQueryParams: ["api_key"] });
 * // ...later: detach();
 */
export function attachLogging(
  client: Client,
  options?: LoggingOptions,
): () => void {
  const { onRequest, onResponse, onError } = createLoggingInterceptors(options);
  const reqId = client.interceptors.request.use(onRequest);
  const resId = client.interceptors.response.use(onResponse);
  const errId = client.interceptors.error.use(onError);
  return () => {
    client.interceptors.request.eject(reqId);
    client.interceptors.response.eject(resId);
    client.interceptors.error.eject(errId);
  };
}

// ---------------------------------------------------------------------------
// Fetch decorators (custom HTTP client)
// ---------------------------------------------------------------------------

/** The Fetch API signature, as accepted by `client.setConfig({ fetch })`. */
export type FetchFn = typeof fetch;

/**
 * A decorator that wraps a `fetch` implementation in another one. Receives the
 * `next` fetch to delegate to and returns a replacement. Compose several with
 * {@link composeFetch}.
 */
export type FetchMiddleware = (next: FetchFn) => FetchFn;

/**
 * Compose a base `fetch` with middlewares, applied left-to-right: the first
 * middleware is the outermost wrapper and runs first.
 *
 *   composeFetch(base, A, B) // A(B(base)) — A sees the call before B
 *
 * The result is a drop-in `fetch` you can pass to the client:
 *
 * @example
 * import { client } from "@diogopms/invoice-express-js";
 * import {
 *   composeFetch, withLogging, withTimeout, withRetry,
 * } from "@diogopms/invoice-express-js/interceptors";
 *
 * client.setConfig({
 *   baseUrl: "https://acme.app.invoicexpress.com",
 *   fetch: composeFetch(
 *     globalThis.fetch,
 *     withLogging(),
 *     withTimeout(10_000),
 *     withRetry({ retries: 2 }),
 *   ),
 * });
 *
 * To plug in a non-global HTTP client, pass it as the base — e.g. undici:
 *
 * @example
 * import { fetch as undiciFetch } from "undici";
 * client.setConfig({ fetch: composeFetch(undiciFetch as typeof fetch, withLogging()) });
 */
export function composeFetch(
  base: FetchFn,
  ...middlewares: FetchMiddleware[]
): FetchFn {
  return middlewares.reduceRight((next, middleware) => middleware(next), base);
}

/** Combine abort signals; aborts as soon as any input signal aborts. */
function anySignal(signals: AbortSignal[]): AbortSignal {
  // AbortSignal.any is available on Node 20.3+; fall back for older 20.x.
  const any = (AbortSignal as { any?: (s: AbortSignal[]) => AbortSignal }).any;
  if (any) return any(signals);

  const controller = new AbortController();
  const onAbort = (event: Event) => {
    controller.abort((event.target as AbortSignal).reason);
  };
  for (const signal of signals) {
    if (signal.aborted) {
      controller.abort(signal.reason);
      break;
    }
    signal.addEventListener("abort", onAbort, { once: true });
  }
  return controller.signal;
}

/** Call `next`, injecting `signal` regardless of whether input is a Request. */
function callWithSignal(
  next: FetchFn,
  input: RequestInfo | URL,
  init: RequestInit | undefined,
  signal: AbortSignal,
): Promise<Response> {
  // The generated client always calls fetch as `fetch(request)` (a Request, no
  // init), so the common path is reconstructing the Request with the new signal.
  if (init === undefined && input instanceof Request) {
    return next(new Request(input, { signal }));
  }
  return next(input, { ...init, signal });
}

/** Read the abort signal already attached to a fetch call, if any. */
function existingSignal(
  input: RequestInfo | URL,
  init: RequestInit | undefined,
): AbortSignal | undefined {
  if (init?.signal) return init.signal;
  if (input instanceof Request && input.signal) return input.signal;
  return undefined;
}

/** Read the HTTP method of a fetch call. */
function methodOf(
  input: RequestInfo | URL,
  init: RequestInit | undefined,
): string {
  if (init?.method) return init.method.toUpperCase();
  if (input instanceof Request) return input.method.toUpperCase();
  return "GET";
}

/** Log every call at the transport level (URL, status, duration, failures). */
export function withLogging(
  logger: Logger = consoleLogger,
  options: { redactQueryParams?: readonly string[] } = {},
): FetchMiddleware {
  const redact = options.redactQueryParams ?? ["api_key"];
  return (next) => async (input, init) => {
    const url = redactUrl(requestUrl(input), redact);
    const method = methodOf(input, init);
    const start = now();
    logger.debug?.("→ fetch", { method, url });
    try {
      const response = await next(input, init);
      logger.info("← fetch", {
        method,
        url,
        status: response.status,
        durationMs: Math.round(now() - start),
      });
      return response;
    } catch (error) {
      logger.error("✗ fetch failed", {
        method,
        url,
        durationMs: Math.round(now() - start),
        error: error instanceof Error ? error.message : error,
      });
      throw error;
    }
  };
}

/**
 * Abort a request that takes longer than `ms` milliseconds. Honors any caller
 * `AbortSignal` too — whichever fires first wins.
 */
export function withTimeout(ms: number): FetchMiddleware {
  return (next) => (input, init) => {
    const timeout = AbortSignal.timeout(ms);
    const existing = existingSignal(input, init);
    const signal = existing ? anySignal([existing, timeout]) : timeout;
    return callWithSignal(next, input, init, signal);
  };
}

export interface RetryContext {
  method: string;
  attempt: number;
  response: Response | undefined;
  error: unknown;
}

export interface RetryOptions {
  /** Maximum number of retries (total attempts = retries + 1). @default 2 */
  retries?: number;
  /**
   * Decide whether to retry. Defaults to a conservative policy: network errors
   * and `5xx` for idempotent methods (GET/HEAD), and `429` for any method
   * (rate-limited requests aren't processed, so they're safe to repeat).
   */
  retryOn?: (context: RetryContext) => boolean;
  /** Delay before attempt `n` (0-based), in ms. @default exponential + jitter */
  backoff?: (attempt: number) => number;
}

function defaultRetryOn(context: RetryContext): boolean {
  const idempotent = context.method === "GET" || context.method === "HEAD";
  if (context.error !== undefined) return idempotent; // network/transport error
  const status = context.response?.status;
  if (status === undefined) return false;
  if (status === 429) return true;
  return idempotent && status >= 500;
}

function defaultBackoff(attempt: number): number {
  const base = Math.min(1000 * 2 ** attempt, 10_000);
  return base / 2 + Math.floor((base / 2) * pseudoJitter(attempt));
}

/** Deterministic jitter in [0, 1) — avoids `Math.random` for predictability. */
function pseudoJitter(attempt: number): number {
  const x = Math.sin(attempt + 1) * 10_000;
  return x - Math.floor(x);
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Retry failed requests with backoff. The request is cloned before each attempt
 * so a consumed body never breaks a retry. The default policy is conservative
 * about non-idempotent methods to avoid duplicate document creation — override
 * `retryOn` if you need different behavior.
 */
export function withRetry(options: RetryOptions = {}): FetchMiddleware {
  const retries = options.retries ?? 2;
  const retryOn = options.retryOn ?? defaultRetryOn;
  const backoff = options.backoff ?? defaultBackoff;

  return (next) => async (input, init) => {
    const method = methodOf(input, init);
    let lastError: unknown;

    for (let attempt = 0; attempt <= retries; attempt++) {
      // Clone per attempt: a Request's body is a one-shot stream.
      const attemptInput = input instanceof Request ? input.clone() : input;

      let response: Response | undefined;
      try {
        response = await next(attemptInput, init);
        lastError = undefined;
      } catch (error) {
        lastError = error;
      }

      const isLastAttempt = attempt === retries;
      if (
        isLastAttempt ||
        !retryOn({ method, attempt, response, error: lastError })
      ) {
        if (lastError !== undefined) throw lastError;
        return response as Response;
      }

      await sleep(backoff(attempt));
    }

    // Unreachable, but satisfies the type checker.
    throw lastError;
  };
}
