// This file is auto-generated by @hey-api/openapi-ts

export const $Tax = {
  type: "object",
  required: ["name", "value"],
  properties: {
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    value: {
      type: "number",
    },
    region: {
      type: "string",
    },
    code: {
      type: "string",
    },
    default_tax: {
      type: "number",
    },
  },
} as const;

export const $TaxResponse = {
  type: "object",
  properties: {
    tax: {
      $ref: "#/components/schemas/Tax",
    },
  },
} as const;

export const $TaxesResponse = {
  type: "object",
  required: ["taxes"],
  properties: {
    taxes: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Tax",
      },
    },
  },
} as const;

export const $Item = {
  type: "object",
  required: ["name", "unit_price", "quantity"],
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    unit_price: {
      type: "number",
    },
    unit: {
      type: "string",
    },
    quantity: {
      type: "integer",
    },
    tax: {
      type: "object",
      properties: {
        id: {
          type: "integer",
        },
        name: {
          type: "string",
        },
        value: {
          type: "number",
        },
      },
    },
    discount: {
      type: "number",
    },
    subtotal: {
      type: "number",
    },
    tax_amount: {
      type: "number",
    },
    discount_amount: {
      type: "number",
    },
    total: {
      type: "number",
    },
  },
} as const;

export const $ItemResponse = {
  type: "object",
  properties: {
    item: {
      $ref: "#/components/schemas/Item",
    },
  },
} as const;

export const $ItensResponse = {
  type: "object",
  required: ["taxes"],
  properties: {
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
  },
} as const;

export const $MBReference = {
  type: "object",
  required: ["entity", "value", "reference"],
  properties: {
    entity: {
      type: "string",
    },
    value: {
      type: "number",
    },
    reference: {
      type: "string",
    },
  },
} as const;

export const $GlobalDiscount = {
  type: "object",
  required: ["value_type", "value"],
  properties: {
    value_type: {
      type: "string",
    },
    value: {
      type: "number",
    },
  },
} as const;

export const $Invoice = {
  type: "object",
  required: [
    "id",
    "status",
    "type",
    "sequence_number",
    "date",
    "due_date",
    "total",
    "client",
    "items",
  ],
  properties: {
    id: {
      type: "integer",
    },
    status: {
      type: "string",
    },
    archived: {
      type: "boolean",
    },
    type: {
      type: "string",
    },
    sequence_number: {
      type: "string",
    },
    inverted_sequence_number: {
      type: "string",
    },
    atcud: {
      type: "string",
    },
    sequence_id: {
      type: "string",
    },
    tax_exemption: {
      type: "string",
    },
    date: {
      type: "string",
      format: "date",
    },
    due_date: {
      type: "string",
      format: "date",
    },
    reference: {
      type: "string",
    },
    observations: {
      type: "string",
    },
    retention: {
      type: "string",
    },
    permalink: {
      type: "string",
    },
    saft_hash: {
      type: "string",
    },
    sum: {
      type: "number",
    },
    discount: {
      type: "number",
    },
    before_taxes: {
      type: "number",
    },
    taxes: {
      type: "number",
    },
    total: {
      type: "number",
    },
    currency: {
      type: "string",
    },
    client: {
      $ref: "#/components/schemas/Client",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
    mb_reference: {
      $ref: "#/components/schemas/MBReference",
    },
    global_discount: {
      $ref: "#/components/schemas/GlobalDiscount",
    },
  },
} as const;

export const $Client = {
  type: "object",
  required: ["id", "name"],
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    email: {
      type: "string",
    },
    address: {
      type: "string",
    },
    city: {
      type: "string",
    },
    postal_code: {
      type: "string",
    },
    fiscal_id: {
      type: "string",
    },
    website: {
      type: "string",
    },
    country: {
      type: "string",
    },
    phone: {
      type: "string",
    },
    fax: {
      type: "string",
    },
    preferred_contact: {
      type: "object",
      properties: {
        name: {
          type: "string",
        },
        email: {
          type: "string",
        },
        phone: {
          type: "string",
        },
      },
    },
    observations: {
      type: "string",
    },
    open_account_link: {
      type: "string",
    },
    send_options: {
      type: "string",
    },
    payment_days: {
      type: "string",
    },
    tax_exemption_code: {
      type: "string",
    },
  },
} as const;

export const $ClientsResponse = {
  type: "object",
  required: ["clients", "pagination"],
  properties: {
    clients: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Client",
      },
    },
    pagination: {
      type: "object",
      required: ["total_entries", "current_page", "total_pages", "per_page"],
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $ClientResponse = {
  type: "object",
  properties: {
    client: {
      $ref: "#/components/schemas/Client",
    },
  },
} as const;

export const $InvoiceReceiptsRequest = {
  type: "object",
  required: ["invoice_receipt"],
  properties: {
    invoice_receipt: {
      type: "object",
      required: ["date", "due_date", "status"],
      properties: {
        date: {
          type: "string",
          format: "date",
        },
        due_date: {
          type: "string",
          format: "date",
        },
        status: {
          type: "string",
        },
        sequence_id: {
          type: "string",
        },
        tax_exemption: {
          type: "string",
        },
        client: {
          type: "object",
          required: ["name"],
          projects: {
            name: {
              type: "string",
            },
          },
        },
        items: {
          type: "array",
          items: {
            $ref: "#/components/schemas/Item",
          },
        },
      },
    },
  },
} as const;

export const $ClientRequest = {
  type: "object",
  required: ["client"],
  properties: {
    client: {
      type: "object",
      required: ["name"],
      properties: {
        name: {
          type: "string",
        },
        code: {
          type: "string",
        },
        email: {
          type: "string",
        },
        language: {
          type: "string",
        },
        address: {
          type: "string",
        },
        city: {
          type: "string",
        },
        postal_code: {
          type: "string",
        },
        country: {
          type: "string",
        },
        fiscal_id: {
          type: "string",
        },
        website: {
          type: "string",
        },
        phone: {
          type: "string",
        },
        fax: {
          type: "string",
        },
        preferred_contact: {
          type: "object",
          properties: {
            name: {
              type: "string",
            },
            email: {
              type: "string",
            },
            phone: {
              type: "string",
            },
          },
        },
        observations: {
          type: "string",
        },
        send_options: {
          type: "string",
        },
      },
    },
  },
} as const;

export const $InvoicesResponse = {
  type: "object",
  required: ["invoices", "pagination"],
  properties: {
    invoices: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Invoice",
      },
    },
    pagination: {
      type: "object",
      required: ["total_entries", "current_page", "total_pages", "per_page"],
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $InvoiceResponse = {
  type: "object",
  required: ["invoice"],
  properties: {
    invoice: {
      $ref: "#/components/schemas/Invoice",
    },
  },
} as const;

export const $ErrorResponse = {
  type: "object",
  properties: {
    error: {
      type: "string",
    },
  },
} as const;
