// This file is auto-generated by @hey-api/openapi-ts

export const $Tax = {
  type: "object",
  required: ["name", "value"],
  properties: {
    id: {
      type: "integer",
    },
    name: {
      type: "string",
    },
    value: {
      type: "number",
    },
    region: {
      type: "string",
    },
    code: {
      type: "string",
    },
    default_tax: {
      type: "number",
    },
  },
} as const;

export const $TaxResponse = {
  type: "object",
  properties: {
    tax: {
      $ref: "#/components/schemas/Tax",
    },
  },
} as const;

export const $TaxesResponse = {
  type: "object",
  required: ["taxes"],
  properties: {
    taxes: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Tax",
      },
    },
  },
} as const;

export const $Item = {
  type: "object",
  required: ["name", "unit_price", "quantity"],
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    unit_price: {
      type: "number",
    },
    unit: {
      type: "string",
    },
    quantity: {
      type: "integer",
    },
    tax: {
      type: "object",
      properties: {
        id: {
          type: "integer",
        },
        name: {
          type: "string",
        },
        value: {
          type: "number",
        },
      },
    },
    discount: {
      type: "number",
    },
    subtotal: {
      type: "number",
    },
    tax_amount: {
      type: "number",
    },
    discount_amount: {
      type: "number",
    },
    total: {
      type: "number",
    },
  },
} as const;

export const $ItemResponse = {
  type: "object",
  properties: {
    item: {
      $ref: "#/components/schemas/Item",
    },
  },
} as const;

export const $ItemsResponse = {
  type: "object",
  required: ["items"],
  properties: {
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
  },
} as const;

export const $MBReference = {
  type: "object",
  required: ["entity", "value", "reference"],
  properties: {
    entity: {
      type: "string",
    },
    value: {
      type: "number",
    },
    reference: {
      type: "string",
    },
  },
} as const;

export const $GlobalDiscount = {
  type: "object",
  required: ["value_type", "value"],
  properties: {
    value_type: {
      type: "string",
    },
    value: {
      type: "number",
    },
  },
} as const;

export const $Invoice = {
  type: "object",
  required: [
    "id",
    "status",
    "type",
    "sequence_number",
    "date",
    "due_date",
    "total",
    "client",
    "items",
  ],
  properties: {
    id: {
      type: "integer",
    },
    status: {
      type: "string",
    },
    archived: {
      type: "boolean",
    },
    type: {
      type: "string",
    },
    sequence_number: {
      type: "string",
    },
    inverted_sequence_number: {
      type: "string",
    },
    atcud: {
      type: "string",
    },
    sequence_id: {
      type: "string",
    },
    tax_exemption: {
      type: "string",
    },
    date: {
      type: "string",
      format: "date",
    },
    due_date: {
      type: "string",
      format: "date",
    },
    reference: {
      type: "string",
    },
    observations: {
      type: "string",
    },
    retention: {
      type: "string",
    },
    permalink: {
      type: "string",
    },
    saft_hash: {
      type: "string",
    },
    sum: {
      type: "number",
    },
    discount: {
      type: "number",
    },
    before_taxes: {
      type: "number",
    },
    taxes: {
      type: "number",
    },
    total: {
      type: "number",
    },
    currency: {
      type: "string",
    },
    client: {
      $ref: "#/components/schemas/Client",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
    mb_reference: {
      $ref: "#/components/schemas/MBReference",
    },
    global_discount: {
      $ref: "#/components/schemas/GlobalDiscount",
    },
  },
} as const;

export const $Client = {
  type: "object",
  required: ["id", "name"],
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    email: {
      type: "string",
    },
    address: {
      type: "string",
    },
    city: {
      type: "string",
    },
    postal_code: {
      type: "string",
    },
    fiscal_id: {
      type: "string",
    },
    website: {
      type: "string",
    },
    country: {
      type: "string",
    },
    phone: {
      type: "string",
    },
    fax: {
      type: "string",
    },
    preferred_contact: {
      type: "object",
      properties: {
        name: {
          type: "string",
        },
        email: {
          type: "string",
        },
        phone: {
          type: "string",
        },
      },
    },
    observations: {
      type: "string",
    },
    open_account_link: {
      type: "string",
    },
    send_options: {
      type: "string",
    },
    payment_days: {
      type: "string",
    },
    tax_exemption_code: {
      type: "string",
    },
  },
} as const;

export const $ClientsResponse = {
  type: "object",
  required: ["clients", "pagination"],
  properties: {
    clients: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Client",
      },
    },
    pagination: {
      type: "object",
      required: ["total_entries", "current_page", "total_pages", "per_page"],
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $ClientResponse = {
  type: "object",
  properties: {
    client: {
      $ref: "#/components/schemas/Client",
    },
  },
} as const;

export const $InvoiceReceiptsRequest = {
  type: "object",
  required: ["invoice_receipt"],
  properties: {
    invoice_receipt: {
      type: "object",
      required: ["date", "due_date", "status"],
      properties: {
        date: {
          type: "string",
          format: "date",
        },
        due_date: {
          type: "string",
          format: "date",
        },
        status: {
          type: "string",
        },
        sequence_id: {
          type: "string",
        },
        tax_exemption: {
          type: "string",
        },
        client: {
          type: "object",
          required: ["name"],
          properties: {
            name: {
              type: "string",
            },
          },
        },
        items: {
          type: "array",
          items: {
            $ref: "#/components/schemas/Item",
          },
        },
      },
    },
  },
} as const;

export const $ClientRequest = {
  type: "object",
  required: ["client"],
  properties: {
    client: {
      type: "object",
      required: ["name"],
      properties: {
        name: {
          type: "string",
        },
        code: {
          type: "string",
        },
        email: {
          type: "string",
        },
        language: {
          type: "string",
        },
        address: {
          type: "string",
        },
        city: {
          type: "string",
        },
        postal_code: {
          type: "string",
        },
        country: {
          type: "string",
        },
        fiscal_id: {
          type: "string",
        },
        website: {
          type: "string",
        },
        phone: {
          type: "string",
        },
        fax: {
          type: "string",
        },
        preferred_contact: {
          type: "object",
          properties: {
            name: {
              type: "string",
            },
            email: {
              type: "string",
            },
            phone: {
              type: "string",
            },
          },
        },
        observations: {
          type: "string",
        },
        send_options: {
          type: "string",
        },
      },
    },
  },
} as const;

export const $InvoicesResponse = {
  type: "object",
  required: ["invoices", "pagination"],
  properties: {
    invoices: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Invoice",
      },
    },
    pagination: {
      type: "object",
      required: ["total_entries", "current_page", "total_pages", "per_page"],
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $InvoiceResponse = {
  type: "object",
  required: ["invoice"],
  properties: {
    invoice: {
      $ref: "#/components/schemas/Invoice",
    },
  },
} as const;

export const $InvoiceRequest = {
  type: "object",
  required: ["invoice"],
  properties: {
    invoice: {
      type: "object",
      required: ["date", "due_date", "client", "items"],
      properties: {
        date: {
          type: "string",
          description: "Document date in dd/mm/yyyy format.",
        },
        due_date: {
          type: "string",
          description: "Due date in dd/mm/yyyy format.",
        },
        reference: {
          type: "string",
        },
        observations: {
          type: "string",
        },
        retention: {
          type: "number",
          description: "Retention percentage (0–99.99).",
        },
        tax_exemption: {
          type: "string",
          description: "Tax exemption code (required when an item has no tax).",
        },
        tax_exemption_reason: {
          type: "string",
        },
        sequence_id: {
          type: "string",
        },
        manual_sequence_number: {
          type: "string",
        },
        currency_code: {
          type: "string",
        },
        rate: {
          type: "string",
          description:
            "Exchange rate, required when currency_code differs from the account currency.",
        },
        mb_reference: {
          type: "boolean",
          description:
            "Whether to generate a Multibanco reference for the document.",
        },
        owner_invoice_id: {
          type: "integer",
          description: "Source document id (e.g. when issuing a credit note).",
        },
        client: {
          type: "object",
          required: ["name"],
          properties: {
            name: {
              type: "string",
            },
            code: {
              type: "string",
            },
            email: {
              type: "string",
            },
            address: {
              type: "string",
            },
            city: {
              type: "string",
            },
            postal_code: {
              type: "string",
            },
            country: {
              type: "string",
            },
            fiscal_id: {
              type: "string",
            },
            website: {
              type: "string",
            },
            phone: {
              type: "string",
            },
            fax: {
              type: "string",
            },
            observations: {
              type: "string",
            },
          },
        },
        items: {
          type: "array",
          items: {
            $ref: "#/components/schemas/Item",
          },
        },
        global_discount: {
          $ref: "#/components/schemas/GlobalDiscount",
        },
      },
    },
    proprietary_uid: {
      type: "string",
      description: "Idempotency key to prevent duplicate document creation.",
    },
  },
} as const;

export const $ItemRequest = {
  type: "object",
  required: ["item"],
  properties: {
    item: {
      type: "object",
      required: ["name", "unit_price"],
      properties: {
        name: {
          type: "string",
        },
        description: {
          type: "string",
        },
        unit_price: {
          type: "number",
        },
        unit: {
          type: "string",
        },
        tax: {
          type: "object",
          properties: {
            name: {
              type: "string",
            },
          },
        },
      },
    },
  },
} as const;

export const $TaxRequest = {
  type: "object",
  required: ["tax"],
  properties: {
    tax: {
      type: "object",
      required: ["name", "value"],
      properties: {
        name: {
          type: "string",
        },
        value: {
          type: "number",
        },
        region: {
          type: "string",
        },
        code: {
          type: "string",
        },
        default_tax: {
          type: "boolean",
        },
      },
    },
  },
} as const;

export const $Address = {
  type: "object",
  properties: {
    detail: {
      type: "string",
    },
    city: {
      type: "string",
    },
    postal_code: {
      type: "string",
    },
    country: {
      type: "string",
    },
  },
} as const;

export const $Guide = {
  type: "object",
  required: ["id", "status", "type", "date", "client", "items"],
  properties: {
    id: {
      type: "integer",
    },
    status: {
      type: "string",
    },
    archived: {
      type: "boolean",
    },
    type: {
      type: "string",
      description: "The guide type (Shipping, Transport or Devolution).",
    },
    sequence_number: {
      type: "string",
    },
    inverted_sequence_number: {
      type: "string",
    },
    atcud: {
      type: "string",
    },
    tax_exemption: {
      type: "string",
    },
    date: {
      type: "string",
      format: "date",
    },
    loaded_at: {
      type: "string",
      description: "Loading date and time (dd/mm/yyyy HH:MM:SS).",
    },
    reference: {
      type: "string",
    },
    observations: {
      type: "string",
    },
    permalink: {
      type: "string",
    },
    saft_hash: {
      type: "string",
    },
    sum: {
      type: "number",
    },
    discount: {
      type: "number",
    },
    before_taxes: {
      type: "number",
    },
    taxes: {
      type: "number",
    },
    total: {
      type: "number",
    },
    currency: {
      type: "string",
    },
    address_from: {
      $ref: "#/components/schemas/Address",
    },
    address_to: {
      $ref: "#/components/schemas/Address",
    },
    client: {
      $ref: "#/components/schemas/Client",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
  },
} as const;

export const $GuideBody = {
  type: "object",
  required: ["date", "client", "items"],
  properties: {
    date: {
      type: "string",
      description: "Document date in dd/mm/yyyy format.",
    },
    loaded_at: {
      type: "string",
      description: "Loading date and time in dd/mm/yyyy HH:MM:SS format.",
    },
    reference: {
      type: "string",
    },
    observations: {
      type: "string",
    },
    tax_exemption: {
      type: "string",
      description: "Tax exemption code (required when an item has no tax).",
    },
    tax_exemption_reason: {
      type: "string",
    },
    sequence_id: {
      type: "string",
    },
    manual_sequence_number: {
      type: "string",
    },
    address_from: {
      $ref: "#/components/schemas/Address",
    },
    address_to: {
      $ref: "#/components/schemas/Address",
    },
    client: {
      type: "object",
      required: ["name"],
      properties: {
        name: {
          type: "string",
        },
        code: {
          type: "string",
        },
        email: {
          type: "string",
        },
        address: {
          type: "string",
        },
        city: {
          type: "string",
        },
        postal_code: {
          type: "string",
        },
        country: {
          type: "string",
        },
        fiscal_id: {
          type: "string",
        },
        website: {
          type: "string",
        },
        phone: {
          type: "string",
        },
        fax: {
          type: "string",
        },
        observations: {
          type: "string",
        },
      },
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
  },
} as const;

export const $GuideRequest = {
  description: `Create/update payload. The root key must match the {guides-type} path
parameter: "shipping" for shippings, "transport" for transports,
"devolution" for devolutions.
`,
  oneOf: [
    {
      type: "object",
      required: ["shipping"],
      properties: {
        shipping: {
          $ref: "#/components/schemas/GuideBody",
        },
      },
    },
    {
      type: "object",
      required: ["transport"],
      properties: {
        transport: {
          $ref: "#/components/schemas/GuideBody",
        },
      },
    },
    {
      type: "object",
      required: ["devolution"],
      properties: {
        devolution: {
          $ref: "#/components/schemas/GuideBody",
        },
      },
    },
  ],
} as const;

export const $GuideResponse = {
  description: `A single guide, wrapped under the key matching its type
("shipping", "transport" or "devolution").
`,
  oneOf: [
    {
      type: "object",
      required: ["shipping"],
      properties: {
        shipping: {
          $ref: "#/components/schemas/Guide",
        },
      },
    },
    {
      type: "object",
      required: ["transport"],
      properties: {
        transport: {
          $ref: "#/components/schemas/Guide",
        },
      },
    },
    {
      type: "object",
      required: ["devolution"],
      properties: {
        devolution: {
          $ref: "#/components/schemas/Guide",
        },
      },
    },
  ],
} as const;

export const $GuideStateRequest = {
  description: `Change-state payload. The root key must match the {guides-type} path
parameter ("shipping", "transport" or "devolution").
`,
  oneOf: [
    {
      type: "object",
      required: ["shipping"],
      properties: {
        shipping: {
          $ref: "#/components/schemas/GuideStateChange",
        },
      },
    },
    {
      type: "object",
      required: ["transport"],
      properties: {
        transport: {
          $ref: "#/components/schemas/GuideStateChange",
        },
      },
    },
    {
      type: "object",
      required: ["devolution"],
      properties: {
        devolution: {
          $ref: "#/components/schemas/GuideStateChange",
        },
      },
    },
  ],
} as const;

export const $GuideStateChange = {
  type: "object",
  required: ["state"],
  properties: {
    state: {
      type: "string",
      enum: ["finalized", "deleted", "canceled"],
      description: "The new state of the guide.",
    },
    message: {
      type: "string",
      description:
        "The reason for changing the state (required for cancellation).",
    },
  },
} as const;

export const $GuidesResponse = {
  type: "object",
  required: ["guides", "pagination"],
  properties: {
    guides: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Guide",
      },
    },
    pagination: {
      type: "object",
      required: ["total_entries", "current_page", "total_pages", "per_page"],
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $Estimate = {
  type: "object",
  required: [
    "id",
    "status",
    "type",
    "date",
    "due_date",
    "total",
    "client",
    "items",
  ],
  properties: {
    id: {
      type: "integer",
    },
    status: {
      type: "string",
    },
    archived: {
      type: "boolean",
    },
    type: {
      type: "string",
      description: "The estimate type (Quote, Proforma or FeesNote).",
    },
    sequence_number: {
      type: "string",
    },
    inverted_sequence_number: {
      type: "string",
    },
    atcud: {
      type: "string",
    },
    tax_exemption: {
      type: "string",
    },
    date: {
      type: "string",
      format: "date",
    },
    due_date: {
      type: "string",
      format: "date",
    },
    reference: {
      type: "string",
    },
    observations: {
      type: "string",
    },
    retention: {
      type: "string",
    },
    permalink: {
      type: "string",
    },
    saft_hash: {
      type: "string",
    },
    sum: {
      type: "number",
    },
    discount: {
      type: "number",
    },
    before_taxes: {
      type: "number",
    },
    taxes: {
      type: "number",
    },
    total: {
      type: "number",
    },
    currency: {
      type: "string",
    },
    client: {
      $ref: "#/components/schemas/Client",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
    global_discount: {
      $ref: "#/components/schemas/GlobalDiscount",
    },
  },
} as const;

export const $EstimateBody = {
  type: "object",
  required: ["date", "due_date", "client", "items"],
  properties: {
    date: {
      type: "string",
      description: "Document date in dd/mm/yyyy format.",
    },
    due_date: {
      type: "string",
      description: "Expiration date in dd/mm/yyyy format.",
    },
    reference: {
      type: "string",
    },
    observations: {
      type: "string",
    },
    retention: {
      type: "number",
      description: "Retention percentage (0–99.99).",
    },
    tax_exemption: {
      type: "string",
      description: "Tax exemption code (required when an item has no tax).",
    },
    tax_exemption_reason: {
      type: "string",
    },
    sequence_id: {
      type: "string",
    },
    manual_sequence_number: {
      type: "string",
    },
    currency_code: {
      type: "string",
    },
    rate: {
      type: "string",
      description:
        "Exchange rate, required when currency_code differs from the account currency.",
    },
    client: {
      type: "object",
      required: ["name"],
      properties: {
        name: {
          type: "string",
        },
        code: {
          type: "string",
        },
        email: {
          type: "string",
        },
        address: {
          type: "string",
        },
        city: {
          type: "string",
        },
        postal_code: {
          type: "string",
        },
        country: {
          type: "string",
        },
        fiscal_id: {
          type: "string",
        },
        website: {
          type: "string",
        },
        phone: {
          type: "string",
        },
        fax: {
          type: "string",
        },
        observations: {
          type: "string",
        },
      },
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
    global_discount: {
      $ref: "#/components/schemas/GlobalDiscount",
    },
  },
} as const;

export const $EstimateRequest = {
  description: `Create/update payload. The root key must match the {estimates-type} path
parameter: "quote" for quotes, "proforma" for proformas, "fees_note" for
fees_notes.
`,
  oneOf: [
    {
      type: "object",
      required: ["quote"],
      properties: {
        quote: {
          $ref: "#/components/schemas/EstimateBody",
        },
      },
    },
    {
      type: "object",
      required: ["proforma"],
      properties: {
        proforma: {
          $ref: "#/components/schemas/EstimateBody",
        },
      },
    },
    {
      type: "object",
      required: ["fees_note"],
      properties: {
        fees_note: {
          $ref: "#/components/schemas/EstimateBody",
        },
      },
    },
  ],
} as const;

export const $EstimateResponse = {
  description: `A single estimate, wrapped under the key matching its type
("quote", "proforma" or "fees_note").
`,
  oneOf: [
    {
      type: "object",
      required: ["quote"],
      properties: {
        quote: {
          $ref: "#/components/schemas/Estimate",
        },
      },
    },
    {
      type: "object",
      required: ["proforma"],
      properties: {
        proforma: {
          $ref: "#/components/schemas/Estimate",
        },
      },
    },
    {
      type: "object",
      required: ["fees_note"],
      properties: {
        fees_note: {
          $ref: "#/components/schemas/Estimate",
        },
      },
    },
  ],
} as const;

export const $EstimateStateRequest = {
  description: `Change-state payload. The root key must match the {estimates-type} path
parameter ("quote", "proforma" or "fees_note").
`,
  oneOf: [
    {
      type: "object",
      required: ["quote"],
      properties: {
        quote: {
          $ref: "#/components/schemas/EstimateStateChange",
        },
      },
    },
    {
      type: "object",
      required: ["proforma"],
      properties: {
        proforma: {
          $ref: "#/components/schemas/EstimateStateChange",
        },
      },
    },
    {
      type: "object",
      required: ["fees_note"],
      properties: {
        fees_note: {
          $ref: "#/components/schemas/EstimateStateChange",
        },
      },
    },
  ],
} as const;

export const $EstimateStateChange = {
  type: "object",
  required: ["state"],
  properties: {
    state: {
      type: "string",
      enum: ["finalized", "deleted", "accepted", "refused", "canceled"],
      description: "The new state of the estimate.",
    },
    message: {
      type: "string",
      description:
        "The reason for changing the state (required for cancellation).",
    },
  },
} as const;

export const $EstimatesResponse = {
  type: "object",
  required: ["estimates", "pagination"],
  properties: {
    estimates: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Estimate",
      },
    },
    pagination: {
      type: "object",
      required: ["total_entries", "current_page", "total_pages", "per_page"],
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $Sequence = {
  type: "object",
  required: ["id", "serie"],
  properties: {
    id: {
      type: "integer",
    },
    serie: {
      type: "string",
      description: 'The series identifier (e.g. "2026").',
    },
    default_sequence: {
      type: "boolean",
      description: "Whether this is the account's current/default sequence.",
    },
    registered: {
      type: "boolean",
      description:
        "Whether the sequence has been registered with the Tax Authority.",
    },
    current_invoice_number: {
      type: "integer",
    },
    current_invoice_receipt_number: {
      type: "integer",
    },
    current_simplified_invoice_number: {
      type: "integer",
    },
    current_credit_note_number: {
      type: "integer",
    },
    current_debit_note_number: {
      type: "integer",
    },
    current_receipt_number: {
      type: "integer",
    },
    current_money_receipt_number: {
      type: "integer",
    },
    current_quote_number: {
      type: "integer",
    },
    current_proforma_number: {
      type: "integer",
    },
    current_fees_note_number: {
      type: "integer",
    },
    current_shipping_number: {
      type: "integer",
    },
    current_transport_number: {
      type: "integer",
    },
    current_devolution_number: {
      type: "integer",
    },
  },
} as const;

export const $SequenceBody = {
  type: "object",
  required: ["serie"],
  properties: {
    serie: {
      type: "string",
      description: 'The series identifier (e.g. "2026").',
    },
    default_sequence: {
      type: "string",
      enum: ["0", "1"],
      description: `Set to "1" to make this the account's current/default sequence.`,
    },
    current_invoice_number: {
      type: "integer",
    },
    current_credit_note_number: {
      type: "integer",
    },
    current_debit_note_number: {
      type: "integer",
    },
    current_receipt_number: {
      type: "integer",
    },
  },
} as const;

export const $SequenceRequest = {
  type: "object",
  required: ["sequence"],
  properties: {
    sequence: {
      $ref: "#/components/schemas/SequenceBody",
    },
  },
} as const;

export const $SequenceResponse = {
  type: "object",
  required: ["sequence"],
  properties: {
    sequence: {
      $ref: "#/components/schemas/Sequence",
    },
  },
} as const;

export const $SequencesResponse = {
  type: "object",
  required: ["sequences"],
  properties: {
    sequences: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Sequence",
      },
    },
  },
} as const;

export const $Account = {
  type: "object",
  required: ["id"],
  properties: {
    id: {
      type: "integer",
    },
    organization_name: {
      type: "string",
    },
    first_name: {
      type: "string",
    },
    last_name: {
      type: "string",
    },
    email: {
      type: "string",
    },
    phone: {
      type: "string",
    },
    fiscal_id: {
      type: "string",
    },
    tax_country: {
      type: "string",
    },
    language: {
      type: "string",
    },
    url: {
      type: "string",
      description: "The account's InvoiceXpress URL (subdomain).",
    },
  },
} as const;

export const $AccountBody = {
  type: "object",
  required: ["organization_name", "email"],
  properties: {
    first_name: {
      type: "string",
    },
    last_name: {
      type: "string",
    },
    organization_name: {
      type: "string",
    },
    email: {
      type: "string",
    },
    password: {
      type: "string",
      description:
        "Required when creating an account for a new user (not for create_already_user).",
    },
    phone: {
      type: "string",
    },
    fiscal_id: {
      type: "string",
    },
    tax_country: {
      type: "string",
      description: 'ISO country code (e.g. "PT").',
    },
    language: {
      type: "string",
      description: 'Language code (e.g. "pt").',
    },
    terms: {
      type: "string",
      enum: ["0", "1"],
      description: "Whether the terms of service were accepted.",
    },
    marketing: {
      type: "string",
      enum: ["0", "1"],
    },
  },
} as const;

export const $AccountRequest = {
  type: "object",
  required: ["account"],
  properties: {
    account: {
      $ref: "#/components/schemas/AccountBody",
    },
  },
} as const;

export const $AccountResponse = {
  type: "object",
  required: ["account"],
  properties: {
    account: {
      $ref: "#/components/schemas/Account",
    },
  },
} as const;

export const $AtCommunicationRequest = {
  type: "object",
  required: ["at_communication"],
  properties: {
    at_communication: {
      type: "object",
      properties: {
        login: {
          type: "string",
          description: "The account's AT (Tax Authority) login.",
        },
        password: {
          type: "string",
          description: "The account's AT (Tax Authority) password.",
        },
      },
    },
  },
} as const;

export const $ErrorResponse = {
  type: "object",
  properties: {
    error: {
      type: "string",
    },
  },
} as const;
