// This file is auto-generated by @hey-api/openapi-ts

export const $Item = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    unit_price: {
      type: "number",
    },
    unit: {
      type: "string",
    },
    quantity: {
      type: "number",
    },
    tax: {
      type: "object",
      properties: {
        id: {
          type: "integer",
        },
        name: {
          type: "string",
        },
        value: {
          type: "number",
        },
      },
    },
    discount: {
      type: "number",
    },
    subtotal: {
      type: "number",
    },
    tax_amount: {
      type: "number",
    },
    discount_amount: {
      type: "number",
    },
    total: {
      type: "number",
    },
  },
} as const;

export const $MBReference = {
  type: "object",
  properties: {
    entity: {
      type: "string",
    },
    value: {
      type: "number",
    },
    reference: {
      type: "string",
    },
  },
} as const;

export const $GlobalDiscount = {
  type: "object",
  properties: {
    value_type: {
      type: "string",
    },
    value: {
      type: "number",
    },
  },
} as const;

export const $Invoice = {
  type: "object",
  properties: {
    id: {
      type: "integer",
    },
    status: {
      type: "string",
    },
    archived: {
      type: "boolean",
    },
    type: {
      type: "string",
    },
    sequence_number: {
      type: "string",
    },
    inverted_sequence_number: {
      type: "string",
    },
    atcud: {
      type: "string",
    },
    sequence_id: {
      type: "string",
    },
    tax_exemption: {
      type: "string",
    },
    date: {
      type: "string",
      format: "date",
    },
    due_date: {
      type: "string",
      format: "date",
    },
    reference: {
      type: "string",
    },
    observations: {
      type: "string",
    },
    retention: {
      type: "string",
    },
    permalink: {
      type: "string",
    },
    saft_hash: {
      type: "string",
    },
    sum: {
      type: "number",
    },
    discount: {
      type: "number",
    },
    before_taxes: {
      type: "number",
    },
    taxes: {
      type: "number",
    },
    total: {
      type: "number",
    },
    currency: {
      type: "string",
    },
    client: {
      $ref: "#/components/schemas/Client",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Item",
      },
    },
    mb_reference: {
      $ref: "#/components/schemas/MBReference",
    },
    global_discount: {
      $ref: "#/components/schemas/GlobalDiscount",
    },
  },
} as const;

export const $Client = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    email: {
      type: "string",
    },
    address: {
      type: "string",
    },
    city: {
      type: "string",
    },
    postal_code: {
      type: "string",
    },
    fiscal_id: {
      type: "string",
    },
    website: {
      type: "string",
    },
    country: {
      type: "string",
    },
    phone: {
      type: "string",
    },
    fax: {
      type: "string",
    },
    preferred_contact: {
      type: "object",
      properties: {
        name: {
          type: "string",
        },
        email: {
          type: "string",
        },
        phone: {
          type: "string",
        },
      },
    },
    observations: {
      type: "string",
    },
    open_account_link: {
      type: "string",
    },
    send_options: {
      type: "string",
    },
    payment_days: {
      type: "string",
    },
    tax_exemption_code: {
      type: "string",
    },
  },
} as const;

export const $ClientsResponse = {
  type: "object",
  properties: {
    clients: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Client",
      },
    },
    pagination: {
      type: "object",
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $ClientResponse = {
  type: "object",
  properties: {
    client: {
      $ref: "#/components/schemas/Client",
    },
  },
} as const;

export const $ClientRequest = {
  type: "object",
  properties: {
    client: {
      type: "object",
      properties: {
        name: {
          type: "string",
        },
        code: {
          type: "string",
        },
        email: {
          type: "string",
        },
        language: {
          type: "string",
        },
        address: {
          type: "string",
        },
        city: {
          type: "string",
        },
        postal_code: {
          type: "string",
        },
        country: {
          type: "string",
        },
        fiscal_id: {
          type: "string",
        },
        website: {
          type: "string",
        },
        phone: {
          type: "string",
        },
        fax: {
          type: "string",
        },
        preferred_contact: {
          type: "object",
          properties: {
            name: {
              type: "string",
            },
            email: {
              type: "string",
            },
            phone: {
              type: "string",
            },
          },
        },
        observations: {
          type: "string",
        },
        send_options: {
          type: "string",
        },
      },
    },
  },
} as const;

export const $InvoicesResponse = {
  type: "object",
  properties: {
    invoices: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "integer",
          },
          status: {
            type: "string",
          },
          archived: {
            type: "boolean",
          },
          type: {
            type: "string",
          },
          sequence_number: {
            type: "string",
          },
          inverted_sequence_number: {
            type: "string",
          },
          date: {
            type: "string",
          },
          due_date: {
            type: "string",
          },
          reference: {
            type: "string",
          },
          observations: {
            type: "string",
          },
          retention: {
            type: "string",
          },
          permalink: {
            type: "string",
          },
          saft_hash: {
            type: "string",
          },
          sum: {
            type: "number",
          },
          discount: {
            type: "number",
          },
          before_taxes: {
            type: "number",
          },
          taxes: {
            type: "number",
          },
          total: {
            type: "number",
          },
          currency: {
            type: "string",
          },
          client: {
            type: "object",
            properties: {
              id: {
                type: "integer",
              },
              name: {
                type: "string",
              },
              country: {
                type: "string",
              },
            },
          },
          items: {
            type: "array",
            items: {
              type: "object",
              properties: {
                name: {
                  type: "string",
                },
                description: {
                  type: "string",
                },
                unit_price: {
                  type: "number",
                },
                unit: {
                  type: "string",
                },
                quantity: {
                  type: "number",
                },
                tax: {
                  type: "object",
                  properties: {
                    id: {
                      type: "integer",
                    },
                    name: {
                      type: "string",
                    },
                    value: {
                      type: "number",
                    },
                  },
                },
                discount: {
                  type: "number",
                },
                subtotal: {
                  type: "number",
                },
                tax_amount: {
                  type: "number",
                },
                discount_amount: {
                  type: "number",
                },
                total: {
                  type: "number",
                },
              },
            },
          },
          sequence_id: {
            type: "string",
          },
          tax_exemption: {
            type: "string",
          },
        },
      },
    },
    pagination: {
      type: "object",
      properties: {
        total_entries: {
          type: "integer",
        },
        current_page: {
          type: "integer",
        },
        total_pages: {
          type: "integer",
        },
        per_page: {
          type: "integer",
        },
      },
    },
  },
} as const;

export const $ErrorResponse = {
  type: "object",
  properties: {
    error: {
      type: "string",
    },
  },
} as const;
