// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client/index.js";
import type {
  DeleteApiV3ClientsByClientIdRegularizationByIdJsonData,
  DeleteApiV3ClientsByClientIdRegularizationByIdJsonErrors,
  DeleteApiV3ClientsByClientIdRegularizationByIdJsonResponses,
  DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonData,
  DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonErrors,
  DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonResponses,
  DeleteItemsByItemIdJsonData,
  DeleteItemsByItemIdJsonErrors,
  DeleteItemsByItemIdJsonResponses,
  DeleteTaxesByTaxIdJsonData,
  DeleteTaxesByTaxIdJsonErrors,
  DeleteTaxesByTaxIdJsonResponses,
  GetApiAccountsByAccountIdGetJsonData,
  GetApiAccountsByAccountIdGetJsonErrors,
  GetApiAccountsByAccountIdGetJsonResponses,
  GetApiExportSaftJsonData,
  GetApiExportSaftJsonErrors,
  GetApiExportSaftJsonResponses,
  GetApiPdfByDocumentIdJsonData,
  GetApiPdfByDocumentIdJsonErrors,
  GetApiPdfByDocumentIdJsonResponses,
  GetApiQrCodesByDocumentIdJsonData,
  GetApiQrCodesByDocumentIdJsonErrors,
  GetApiQrCodesByDocumentIdJsonResponses,
  GetApiV3ClientsByClientIdBalanceJsonData,
  GetApiV3ClientsByClientIdBalanceJsonErrors,
  GetApiV3ClientsByClientIdBalanceJsonResponses,
  GetApiV3ClientsByClientIdRegularizationJsonData,
  GetApiV3ClientsByClientIdRegularizationJsonErrors,
  GetApiV3ClientsByClientIdRegularizationJsonResponses,
  GetByEstimatesTypeByDocumentIdJsonData,
  GetByEstimatesTypeByDocumentIdJsonErrors,
  GetByEstimatesTypeByDocumentIdJsonResponses,
  GetByGuidesTypeByDocumentIdJsonData,
  GetByGuidesTypeByDocumentIdJsonErrors,
  GetByGuidesTypeByDocumentIdJsonResponses,
  GetClientsByClientIdJsonData,
  GetClientsByClientIdJsonErrors,
  GetClientsByClientIdJsonResponses,
  GetClientsFindByCodeJsonData,
  GetClientsFindByCodeJsonErrors,
  GetClientsFindByCodeJsonResponses,
  GetClientsFindByNameJsonData,
  GetClientsFindByNameJsonErrors,
  GetClientsFindByNameJsonResponses,
  GetClientsJsonData,
  GetClientsJsonErrors,
  GetClientsJsonResponses,
  GetDocumentByDocumentIdRelatedDocumentsJsonData,
  GetDocumentByDocumentIdRelatedDocumentsJsonErrors,
  GetDocumentByDocumentIdRelatedDocumentsJsonResponses,
  GetEstimatesJsonData,
  GetEstimatesJsonErrors,
  GetEstimatesJsonResponses,
  GetGuidesJsonData,
  GetGuidesJsonErrors,
  GetGuidesJsonResponses,
  GetInvoiceReceiptsByDocumentIdJsonData,
  GetInvoiceReceiptsByDocumentIdJsonErrors,
  GetInvoiceReceiptsByDocumentIdJsonResponses,
  GetInvoicesByDocumentIdJsonData,
  GetInvoicesByDocumentIdJsonErrors,
  GetInvoicesByDocumentIdJsonResponses,
  GetInvoicesJsonData,
  GetInvoicesJsonErrors,
  GetInvoicesJsonResponses,
  GetItemsByItemIdJsonData,
  GetItemsByItemIdJsonErrors,
  GetItemsByItemIdJsonResponses,
  GetItemsJsonData,
  GetItemsJsonErrors,
  GetItemsJsonResponses,
  GetSequencesBySequenceIdJsonData,
  GetSequencesBySequenceIdJsonErrors,
  GetSequencesBySequenceIdJsonResponses,
  GetSequencesJsonData,
  GetSequencesJsonErrors,
  GetSequencesJsonResponses,
  GetTaxesByTaxIdJsonData,
  GetTaxesByTaxIdJsonErrors,
  GetTaxesByTaxIdJsonResponses,
  GetTaxesJsonData,
  GetTaxesJsonErrors,
  GetTaxesJsonResponses,
  PostApiAccountsCreateAlreadyUserJsonData,
  PostApiAccountsCreateAlreadyUserJsonErrors,
  PostApiAccountsCreateAlreadyUserJsonResponses,
  PostApiAccountsCreateJsonData,
  PostApiAccountsCreateJsonErrors,
  PostApiAccountsCreateJsonResponses,
  PostApiV3AccountsAtCommunicationJsonData,
  PostApiV3AccountsAtCommunicationJsonErrors,
  PostApiV3AccountsAtCommunicationJsonResponses,
  PostApiV3ClientsByClientIdRegularizationJsonData,
  PostApiV3ClientsByClientIdRegularizationJsonErrors,
  PostApiV3ClientsByClientIdRegularizationJsonResponses,
  PostApiV3ClientsByClientIdTreasuryMovementsJsonData,
  PostApiV3ClientsByClientIdTreasuryMovementsJsonErrors,
  PostApiV3ClientsByClientIdTreasuryMovementsJsonResponses,
  PostByEstimatesTypeJsonData,
  PostByEstimatesTypeJsonErrors,
  PostByEstimatesTypeJsonResponses,
  PostByGuidesTypeJsonData,
  PostByGuidesTypeJsonErrors,
  PostByGuidesTypeJsonResponses,
  PostClientsByClientIdInvoicesJsonData,
  PostClientsByClientIdInvoicesJsonErrors,
  PostClientsByClientIdInvoicesJsonResponses,
  PostClientsJsonData,
  PostClientsJsonErrors,
  PostClientsJsonResponses,
  PostDocumentsByDocumentIdPartialPaymentsJsonData,
  PostDocumentsByDocumentIdPartialPaymentsJsonErrors,
  PostDocumentsByDocumentIdPartialPaymentsJsonResponses,
  PostInvoiceReceiptsJsonData,
  PostInvoiceReceiptsJsonErrors,
  PostInvoiceReceiptsJsonResponses,
  PostInvoicesJsonData,
  PostInvoicesJsonErrors,
  PostInvoicesJsonResponses,
  PostItemsJsonData,
  PostItemsJsonErrors,
  PostItemsJsonResponses,
  PostSequencesJsonData,
  PostSequencesJsonErrors,
  PostSequencesJsonResponses,
  PostTaxesJsonData,
  PostTaxesJsonErrors,
  PostTaxesJsonResponses,
  PutApiAccountsByAccountIdUpdateJsonData,
  PutApiAccountsByAccountIdUpdateJsonErrors,
  PutApiAccountsByAccountIdUpdateJsonResponses,
  PutApiV3ClientsByClientIdInitialBalanceJsonData,
  PutApiV3ClientsByClientIdInitialBalanceJsonErrors,
  PutApiV3ClientsByClientIdInitialBalanceJsonResponses,
  PutByEstimatesTypeByDocumentIdChangeStateJsonData,
  PutByEstimatesTypeByDocumentIdChangeStateJsonErrors,
  PutByEstimatesTypeByDocumentIdChangeStateJsonResponses,
  PutByEstimatesTypeByDocumentIdEmailDocumentJsonData,
  PutByEstimatesTypeByDocumentIdEmailDocumentJsonErrors,
  PutByEstimatesTypeByDocumentIdEmailDocumentJsonResponses,
  PutByEstimatesTypeByDocumentIdJsonData,
  PutByEstimatesTypeByDocumentIdJsonErrors,
  PutByEstimatesTypeByDocumentIdJsonResponses,
  PutByGuidesTypeByDocumentIdChangeStateJsonData,
  PutByGuidesTypeByDocumentIdChangeStateJsonErrors,
  PutByGuidesTypeByDocumentIdChangeStateJsonResponses,
  PutByGuidesTypeByDocumentIdEmailDocumentJsonData,
  PutByGuidesTypeByDocumentIdEmailDocumentJsonErrors,
  PutByGuidesTypeByDocumentIdEmailDocumentJsonResponses,
  PutByGuidesTypeByDocumentIdJsonData,
  PutByGuidesTypeByDocumentIdJsonErrors,
  PutByGuidesTypeByDocumentIdJsonResponses,
  PutClientsByClientIdJsonData,
  PutClientsByClientIdJsonErrors,
  PutClientsByClientIdJsonResponses,
  PutInvoiceReceiptsByDocumentIdChangeStateJsonData,
  PutInvoiceReceiptsByDocumentIdChangeStateJsonErrors,
  PutInvoiceReceiptsByDocumentIdChangeStateJsonResponses,
  PutInvoiceReceiptsByDocumentIdEmailDocumentJsonData,
  PutInvoiceReceiptsByDocumentIdEmailDocumentJsonErrors,
  PutInvoiceReceiptsByDocumentIdEmailDocumentJsonResponses,
  PutInvoicesByDocumentIdChangeStateJsonData,
  PutInvoicesByDocumentIdChangeStateJsonErrors,
  PutInvoicesByDocumentIdChangeStateJsonResponses,
  PutInvoicesByDocumentIdJsonData,
  PutInvoicesByDocumentIdJsonErrors,
  PutInvoicesByDocumentIdJsonResponses,
  PutItemsByItemIdJsonData,
  PutItemsByItemIdJsonErrors,
  PutItemsByItemIdJsonResponses,
  PutReceiptsByReceiptIdChangeStateJsonData,
  PutReceiptsByReceiptIdChangeStateJsonErrors,
  PutReceiptsByReceiptIdChangeStateJsonResponses,
  PutSequencesBySequenceIdRegisterJsonData,
  PutSequencesBySequenceIdRegisterJsonErrors,
  PutSequencesBySequenceIdRegisterJsonResponses,
  PutSequencesBySequenceIdSetCurrentJsonData,
  PutSequencesBySequenceIdSetCurrentJsonErrors,
  PutSequencesBySequenceIdSetCurrentJsonResponses,
  PutTaxesByTaxIdJsonData,
  PutTaxesByTaxIdJsonErrors,
  PutTaxesByTaxIdJsonResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Send document by email
 */
export const putInvoiceReceiptsByDocumentIdEmailDocumentJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutInvoiceReceiptsByDocumentIdEmailDocumentJsonData,
    ThrowOnError
  >,
): RequestResult<
  PutInvoiceReceiptsByDocumentIdEmailDocumentJsonResponses,
  PutInvoiceReceiptsByDocumentIdEmailDocumentJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutInvoiceReceiptsByDocumentIdEmailDocumentJsonResponses,
    PutInvoiceReceiptsByDocumentIdEmailDocumentJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoice_receipts/{document-id}/email-document.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the state of a document
 *
 * Changes the state of an invoice, simplified_invoice, invoice_receipt, credit_note, or debit_note.
 */
export const putInvoiceReceiptsByDocumentIdChangeStateJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutInvoiceReceiptsByDocumentIdChangeStateJsonData,
    ThrowOnError
  >,
): RequestResult<
  PutInvoiceReceiptsByDocumentIdChangeStateJsonResponses,
  PutInvoiceReceiptsByDocumentIdChangeStateJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutInvoiceReceiptsByDocumentIdChangeStateJsonResponses,
    PutInvoiceReceiptsByDocumentIdChangeStateJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoice_receipts/{document-id}/change-state.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Invoice
 */
export const getInvoiceReceiptsByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetInvoiceReceiptsByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  GetInvoiceReceiptsByDocumentIdJsonResponses,
  GetInvoiceReceiptsByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetInvoiceReceiptsByDocumentIdJsonResponses,
    GetInvoiceReceiptsByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoice_receipts/{document-id}.json",
    ...options,
  });

/**
 * Generate PDF
 */
export const getApiPdfByDocumentIdJson = <ThrowOnError extends boolean = false>(
  options: Options<GetApiPdfByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  GetApiPdfByDocumentIdJsonResponses,
  GetApiPdfByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiPdfByDocumentIdJsonResponses,
    GetApiPdfByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/pdf/{document-id}.json",
    ...options,
  });

/**
 * Create an invoice_receipts
 */
export const postInvoiceReceiptsJson = <ThrowOnError extends boolean = false>(
  options: Options<PostInvoiceReceiptsJsonData, ThrowOnError>,
): RequestResult<
  PostInvoiceReceiptsJsonResponses,
  PostInvoiceReceiptsJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostInvoiceReceiptsJsonResponses,
    PostInvoiceReceiptsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoice_receipts.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all invoices
 */
export const getInvoicesJson = <ThrowOnError extends boolean = false>(
  options: Options<GetInvoicesJsonData, ThrowOnError>,
): RequestResult<
  GetInvoicesJsonResponses,
  GetInvoicesJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetInvoicesJsonResponses,
    GetInvoicesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoices.json",
    ...options,
  });

/**
 * Create an invoice
 *
 * Creates an invoice. Use the matching document-type endpoint for other documents (e.g. simplified_invoices, credit_notes, debit_notes).
 */
export const postInvoicesJson = <ThrowOnError extends boolean = false>(
  options: Options<PostInvoicesJsonData, ThrowOnError>,
): RequestResult<
  PostInvoicesJsonResponses,
  PostInvoicesJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostInvoicesJsonResponses,
    PostInvoicesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoices.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get an invoice
 */
export const getInvoicesByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetInvoicesByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  GetInvoicesByDocumentIdJsonResponses,
  GetInvoicesByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetInvoicesByDocumentIdJsonResponses,
    GetInvoicesByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoices/{document-id}.json",
    ...options,
  });

/**
 * Update an invoice
 *
 * Updates a draft invoice. Only invoices in the draft state can be updated.
 */
export const putInvoicesByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutInvoicesByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  PutInvoicesByDocumentIdJsonResponses,
  PutInvoicesByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutInvoicesByDocumentIdJsonResponses,
    PutInvoicesByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoices/{document-id}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the state of an invoice
 *
 * Changes the state of an invoice (finalized, deleted, canceled, settled).
 */
export const putInvoicesByDocumentIdChangeStateJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutInvoicesByDocumentIdChangeStateJsonData, ThrowOnError>,
): RequestResult<
  PutInvoicesByDocumentIdChangeStateJsonResponses,
  PutInvoicesByDocumentIdChangeStateJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutInvoicesByDocumentIdChangeStateJsonResponses,
    PutInvoicesByDocumentIdChangeStateJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/invoices/{document-id}/change-state.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List related documents
 *
 * Returns the documents (receipts, credit notes, debit notes) related to the given document.
 */
export const getDocumentByDocumentIdRelatedDocumentsJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetDocumentByDocumentIdRelatedDocumentsJsonData,
    ThrowOnError
  >,
): RequestResult<
  GetDocumentByDocumentIdRelatedDocumentsJsonResponses,
  GetDocumentByDocumentIdRelatedDocumentsJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDocumentByDocumentIdRelatedDocumentsJsonResponses,
    GetDocumentByDocumentIdRelatedDocumentsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/document/{document-id}/related_documents.json",
    ...options,
  });

/**
 * Generate a payment (receipt)
 *
 * Generates a receipt for a (partial) payment of an invoice or simplified invoice.
 */
export const postDocumentsByDocumentIdPartialPaymentsJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PostDocumentsByDocumentIdPartialPaymentsJsonData,
    ThrowOnError
  >,
): RequestResult<
  PostDocumentsByDocumentIdPartialPaymentsJsonResponses,
  PostDocumentsByDocumentIdPartialPaymentsJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostDocumentsByDocumentIdPartialPaymentsJsonResponses,
    PostDocumentsByDocumentIdPartialPaymentsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/documents/{document-id}/partial_payments.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Cancel a payment (receipt)
 *
 * Cancels a payment by changing the state of its receipt to canceled.
 */
export const putReceiptsByReceiptIdChangeStateJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutReceiptsByReceiptIdChangeStateJsonData, ThrowOnError>,
): RequestResult<
  PutReceiptsByReceiptIdChangeStateJsonResponses,
  PutReceiptsByReceiptIdChangeStateJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutReceiptsByReceiptIdChangeStateJsonResponses,
    PutReceiptsByReceiptIdChangeStateJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/receipts/{receipt-id}/change-state.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all clients
 *
 * Retrieves a list of clients.
 */
export const getClientsJson = <ThrowOnError extends boolean = false>(
  options: Options<GetClientsJsonData, ThrowOnError>,
): RequestResult<GetClientsJsonResponses, GetClientsJsonErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetClientsJsonResponses,
    GetClientsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/clients.json",
    ...options,
  });

/**
 * Create a new client
 *
 * Creates a new client.
 */
export const postClientsJson = <ThrowOnError extends boolean = false>(
  options: Options<PostClientsJsonData, ThrowOnError>,
): RequestResult<
  PostClientsJsonResponses,
  PostClientsJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostClientsJsonResponses,
    PostClientsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/clients.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a client by ID
 *
 * Retrieves a client by their ID.
 */
export const getClientsByClientIdJson = <ThrowOnError extends boolean = false>(
  options: Options<GetClientsByClientIdJsonData, ThrowOnError>,
): RequestResult<
  GetClientsByClientIdJsonResponses,
  GetClientsByClientIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetClientsByClientIdJsonResponses,
    GetClientsByClientIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/clients/{client-id}.json",
    ...options,
  });

/**
 * Update a client by ID
 *
 * Updates a client's information by their ID.
 */
export const putClientsByClientIdJson = <ThrowOnError extends boolean = false>(
  options: Options<PutClientsByClientIdJsonData, ThrowOnError>,
): RequestResult<
  PutClientsByClientIdJsonResponses,
  PutClientsByClientIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutClientsByClientIdJsonResponses,
    PutClientsByClientIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/clients/{client-id}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Find client by name
 *
 * Retrieves a client by their name.
 */
export const getClientsFindByNameJson = <ThrowOnError extends boolean = false>(
  options: Options<GetClientsFindByNameJsonData, ThrowOnError>,
): RequestResult<
  GetClientsFindByNameJsonResponses,
  GetClientsFindByNameJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetClientsFindByNameJsonResponses,
    GetClientsFindByNameJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/clients/find-by-name.json",
    ...options,
  });

/**
 * Find client by code
 *
 * Retrieves a client by their code.
 */
export const getClientsFindByCodeJson = <ThrowOnError extends boolean = false>(
  options: Options<GetClientsFindByCodeJsonData, ThrowOnError>,
): RequestResult<
  GetClientsFindByCodeJsonResponses,
  GetClientsFindByCodeJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetClientsFindByCodeJsonResponses,
    GetClientsFindByCodeJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/clients/find-by-code.json",
    ...options,
  });

/**
 * List invoices for a client
 *
 * Retrieves a list of invoices for a specific client.
 */
export const postClientsByClientIdInvoicesJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostClientsByClientIdInvoicesJsonData, ThrowOnError>,
): RequestResult<
  PostClientsByClientIdInvoicesJsonResponses,
  PostClientsByClientIdInvoicesJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostClientsByClientIdInvoicesJsonResponses,
    PostClientsByClientIdInvoicesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/clients/{client-id}/invoices.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Export SAF-T
 *
 * Generates the SAF-T file for a specific date (month and years). The first response given will have a HTTP 202 code, meaning the generation was started. You need to keep requesting until you get a response with HTTP status code 200, and the URL to download the file in the message body.
 */
export const getApiExportSaftJson = <ThrowOnError extends boolean = false>(
  options: Options<GetApiExportSaftJsonData, ThrowOnError>,
): RequestResult<
  GetApiExportSaftJsonResponses,
  GetApiExportSaftJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiExportSaftJsonResponses,
    GetApiExportSaftJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/export_saft.json",
    ...options,
  });

/**
 * List all taxes
 *
 * Retrieves a list of taxes.
 */
export const getTaxesJson = <ThrowOnError extends boolean = false>(
  options: Options<GetTaxesJsonData, ThrowOnError>,
): RequestResult<GetTaxesJsonResponses, GetTaxesJsonErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetTaxesJsonResponses,
    GetTaxesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/taxes.json",
    ...options,
  });

/**
 * Create a new tax
 *
 * Creates a new tax.
 */
export const postTaxesJson = <ThrowOnError extends boolean = false>(
  options: Options<PostTaxesJsonData, ThrowOnError>,
): RequestResult<PostTaxesJsonResponses, PostTaxesJsonErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostTaxesJsonResponses,
    PostTaxesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/taxes.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a tax by ID
 *
 * Deletes a tax by its ID.
 */
export const deleteTaxesByTaxIdJson = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTaxesByTaxIdJsonData, ThrowOnError>,
): RequestResult<
  DeleteTaxesByTaxIdJsonResponses,
  DeleteTaxesByTaxIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTaxesByTaxIdJsonResponses,
    DeleteTaxesByTaxIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/taxes/{tax-id}.json",
    ...options,
  });

/**
 * Get a tax by ID
 *
 * Retrieves a tax by their ID.
 */
export const getTaxesByTaxIdJson = <ThrowOnError extends boolean = false>(
  options: Options<GetTaxesByTaxIdJsonData, ThrowOnError>,
): RequestResult<
  GetTaxesByTaxIdJsonResponses,
  GetTaxesByTaxIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTaxesByTaxIdJsonResponses,
    GetTaxesByTaxIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/taxes/{tax-id}.json",
    ...options,
  });

/**
 * Update a tax by ID
 *
 * Updates a tax's information by its ID.
 */
export const putTaxesByTaxIdJson = <ThrowOnError extends boolean = false>(
  options: Options<PutTaxesByTaxIdJsonData, ThrowOnError>,
): RequestResult<
  PutTaxesByTaxIdJsonResponses,
  PutTaxesByTaxIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutTaxesByTaxIdJsonResponses,
    PutTaxesByTaxIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/taxes/{tax-id}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all items
 *
 * Retrieves a list of items.
 */
export const getItemsJson = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsJsonData, ThrowOnError>,
): RequestResult<GetItemsJsonResponses, GetItemsJsonErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetItemsJsonResponses,
    GetItemsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/items.json",
    ...options,
  });

/**
 * Create a new item
 *
 * Creates a new item.
 */
export const postItemsJson = <ThrowOnError extends boolean = false>(
  options: Options<PostItemsJsonData, ThrowOnError>,
): RequestResult<PostItemsJsonResponses, PostItemsJsonErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostItemsJsonResponses,
    PostItemsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/items.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an item by ID
 *
 * Deletes an item by its ID.
 */
export const deleteItemsByItemIdJson = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemsByItemIdJsonData, ThrowOnError>,
): RequestResult<
  DeleteItemsByItemIdJsonResponses,
  DeleteItemsByItemIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteItemsByItemIdJsonResponses,
    DeleteItemsByItemIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/items/{item-id}.json",
    ...options,
  });

/**
 * Get a item by ID
 *
 * Retrieves a item by their ID.
 */
export const getItemsByItemIdJson = <ThrowOnError extends boolean = false>(
  options: Options<GetItemsByItemIdJsonData, ThrowOnError>,
): RequestResult<
  GetItemsByItemIdJsonResponses,
  GetItemsByItemIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetItemsByItemIdJsonResponses,
    GetItemsByItemIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/items/{item-id}.json",
    ...options,
  });

/**
 * Update an item by ID
 *
 * Updates an item's information by its ID.
 */
export const putItemsByItemIdJson = <ThrowOnError extends boolean = false>(
  options: Options<PutItemsByItemIdJsonData, ThrowOnError>,
): RequestResult<
  PutItemsByItemIdJsonResponses,
  PutItemsByItemIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutItemsByItemIdJsonResponses,
    PutItemsByItemIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/items/{item-id}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all guides
 *
 * Retrieves a list of guides (shippings, transports and devolutions).
 */
export const getGuidesJson = <ThrowOnError extends boolean = false>(
  options: Options<GetGuidesJsonData, ThrowOnError>,
): RequestResult<GetGuidesJsonResponses, GetGuidesJsonErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetGuidesJsonResponses,
    GetGuidesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/guides.json",
    ...options,
  });

/**
 * Get the QR code of a document
 *
 * Returns the QR code image URL for a finalized document.
 */
export const getApiQrCodesByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiQrCodesByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  GetApiQrCodesByDocumentIdJsonResponses,
  GetApiQrCodesByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiQrCodesByDocumentIdJsonResponses,
    GetApiQrCodesByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/qr_codes/{document-id}.json",
    ...options,
  });

/**
 * Create a guide
 *
 * Creates a guide of the given type (shippings, transports or devolutions).
 */
export const postByGuidesTypeJson = <ThrowOnError extends boolean = false>(
  options: Options<PostByGuidesTypeJsonData, ThrowOnError>,
): RequestResult<
  PostByGuidesTypeJsonResponses,
  PostByGuidesTypeJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostByGuidesTypeJsonResponses,
    PostByGuidesTypeJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{guides-type}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a guide
 */
export const getByGuidesTypeByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetByGuidesTypeByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  GetByGuidesTypeByDocumentIdJsonResponses,
  GetByGuidesTypeByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetByGuidesTypeByDocumentIdJsonResponses,
    GetByGuidesTypeByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{guides-type}/{document-id}.json",
    ...options,
  });

/**
 * Update a guide
 *
 * Updates a draft guide. Only guides in the draft state can be updated.
 */
export const putByGuidesTypeByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutByGuidesTypeByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  PutByGuidesTypeByDocumentIdJsonResponses,
  PutByGuidesTypeByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutByGuidesTypeByDocumentIdJsonResponses,
    PutByGuidesTypeByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{guides-type}/{document-id}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the state of a guide
 *
 * Changes the state of a guide (finalized, deleted, canceled).
 */
export const putByGuidesTypeByDocumentIdChangeStateJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutByGuidesTypeByDocumentIdChangeStateJsonData,
    ThrowOnError
  >,
): RequestResult<
  PutByGuidesTypeByDocumentIdChangeStateJsonResponses,
  PutByGuidesTypeByDocumentIdChangeStateJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutByGuidesTypeByDocumentIdChangeStateJsonResponses,
    PutByGuidesTypeByDocumentIdChangeStateJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{guides-type}/{document-id}/change-state.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Send guide by email
 */
export const putByGuidesTypeByDocumentIdEmailDocumentJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutByGuidesTypeByDocumentIdEmailDocumentJsonData,
    ThrowOnError
  >,
): RequestResult<
  PutByGuidesTypeByDocumentIdEmailDocumentJsonResponses,
  PutByGuidesTypeByDocumentIdEmailDocumentJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutByGuidesTypeByDocumentIdEmailDocumentJsonResponses,
    PutByGuidesTypeByDocumentIdEmailDocumentJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{guides-type}/{document-id}/email-document.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all estimates
 *
 * Retrieves a list of estimates (quotes, proformas and fees notes).
 */
export const getEstimatesJson = <ThrowOnError extends boolean = false>(
  options: Options<GetEstimatesJsonData, ThrowOnError>,
): RequestResult<
  GetEstimatesJsonResponses,
  GetEstimatesJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetEstimatesJsonResponses,
    GetEstimatesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/estimates.json",
    ...options,
  });

/**
 * Create an estimate
 *
 * Creates an estimate of the given type (quotes, proformas or fees_notes).
 */
export const postByEstimatesTypeJson = <ThrowOnError extends boolean = false>(
  options: Options<PostByEstimatesTypeJsonData, ThrowOnError>,
): RequestResult<
  PostByEstimatesTypeJsonResponses,
  PostByEstimatesTypeJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostByEstimatesTypeJsonResponses,
    PostByEstimatesTypeJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{estimates-type}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get an estimate
 */
export const getByEstimatesTypeByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetByEstimatesTypeByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  GetByEstimatesTypeByDocumentIdJsonResponses,
  GetByEstimatesTypeByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetByEstimatesTypeByDocumentIdJsonResponses,
    GetByEstimatesTypeByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{estimates-type}/{document-id}.json",
    ...options,
  });

/**
 * Update an estimate
 *
 * Updates a draft estimate. Only estimates in the draft state can be updated.
 */
export const putByEstimatesTypeByDocumentIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutByEstimatesTypeByDocumentIdJsonData, ThrowOnError>,
): RequestResult<
  PutByEstimatesTypeByDocumentIdJsonResponses,
  PutByEstimatesTypeByDocumentIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutByEstimatesTypeByDocumentIdJsonResponses,
    PutByEstimatesTypeByDocumentIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{estimates-type}/{document-id}.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the state of an estimate
 *
 * Changes the state of an estimate (finalized, deleted, accepted, refused, canceled).
 */
export const putByEstimatesTypeByDocumentIdChangeStateJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutByEstimatesTypeByDocumentIdChangeStateJsonData,
    ThrowOnError
  >,
): RequestResult<
  PutByEstimatesTypeByDocumentIdChangeStateJsonResponses,
  PutByEstimatesTypeByDocumentIdChangeStateJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutByEstimatesTypeByDocumentIdChangeStateJsonResponses,
    PutByEstimatesTypeByDocumentIdChangeStateJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{estimates-type}/{document-id}/change-state.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Send estimate by email
 */
export const putByEstimatesTypeByDocumentIdEmailDocumentJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutByEstimatesTypeByDocumentIdEmailDocumentJsonData,
    ThrowOnError
  >,
): RequestResult<
  PutByEstimatesTypeByDocumentIdEmailDocumentJsonResponses,
  PutByEstimatesTypeByDocumentIdEmailDocumentJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutByEstimatesTypeByDocumentIdEmailDocumentJsonResponses,
    PutByEstimatesTypeByDocumentIdEmailDocumentJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/{estimates-type}/{document-id}/email-document.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all sequences
 *
 * Retrieves the list of document sequences for the account.
 */
export const getSequencesJson = <ThrowOnError extends boolean = false>(
  options: Options<GetSequencesJsonData, ThrowOnError>,
): RequestResult<
  GetSequencesJsonResponses,
  GetSequencesJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSequencesJsonResponses,
    GetSequencesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/sequences.json",
    ...options,
  });

/**
 * Create a sequence
 *
 * Creates a new document sequence.
 */
export const postSequencesJson = <ThrowOnError extends boolean = false>(
  options: Options<PostSequencesJsonData, ThrowOnError>,
): RequestResult<
  PostSequencesJsonResponses,
  PostSequencesJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostSequencesJsonResponses,
    PostSequencesJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/sequences.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a sequence
 */
export const getSequencesBySequenceIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSequencesBySequenceIdJsonData, ThrowOnError>,
): RequestResult<
  GetSequencesBySequenceIdJsonResponses,
  GetSequencesBySequenceIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSequencesBySequenceIdJsonResponses,
    GetSequencesBySequenceIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/sequences/{sequence-id}.json",
    ...options,
  });

/**
 * Register a sequence
 *
 * Registers a document sequence with the Tax Authority (AT). Requires AT credentials configured on the account.
 */
export const putSequencesBySequenceIdRegisterJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutSequencesBySequenceIdRegisterJsonData, ThrowOnError>,
): RequestResult<
  PutSequencesBySequenceIdRegisterJsonResponses,
  PutSequencesBySequenceIdRegisterJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutSequencesBySequenceIdRegisterJsonResponses,
    PutSequencesBySequenceIdRegisterJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/sequences/{sequence-id}/register.json",
    ...options,
  });

/**
 * Set a sequence as current
 *
 * Sets the given sequence as the account's current (default) sequence.
 */
export const putSequencesBySequenceIdSetCurrentJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutSequencesBySequenceIdSetCurrentJsonData, ThrowOnError>,
): RequestResult<
  PutSequencesBySequenceIdSetCurrentJsonResponses,
  PutSequencesBySequenceIdSetCurrentJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutSequencesBySequenceIdSetCurrentJsonResponses,
    PutSequencesBySequenceIdSetCurrentJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/sequences/{sequence-id}/set_current.json",
    ...options,
  });

/**
 * Create an account
 *
 * Creates a new account together with its owner user. Used by partners/resellers.
 */
export const postApiAccountsCreateJson = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAccountsCreateJsonData, ThrowOnError>,
): RequestResult<
  PostApiAccountsCreateJsonResponses,
  PostApiAccountsCreateJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAccountsCreateJsonResponses,
    PostApiAccountsCreateJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/accounts/create.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create an account for an existing user
 *
 * Creates a new account and associates it with an already-existing user.
 */
export const postApiAccountsCreateAlreadyUserJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiAccountsCreateAlreadyUserJsonData, ThrowOnError>,
): RequestResult<
  PostApiAccountsCreateAlreadyUserJsonResponses,
  PostApiAccountsCreateAlreadyUserJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAccountsCreateAlreadyUserJsonResponses,
    PostApiAccountsCreateAlreadyUserJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/accounts/create_already_user.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get an account
 */
export const getApiAccountsByAccountIdGetJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiAccountsByAccountIdGetJsonData, ThrowOnError>,
): RequestResult<
  GetApiAccountsByAccountIdGetJsonResponses,
  GetApiAccountsByAccountIdGetJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiAccountsByAccountIdGetJsonResponses,
    GetApiAccountsByAccountIdGetJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/accounts/{account-id}/get.json",
    ...options,
  });

/**
 * Update an account
 *
 * Updates an existing account.
 */
export const putApiAccountsByAccountIdUpdateJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutApiAccountsByAccountIdUpdateJsonData, ThrowOnError>,
): RequestResult<
  PutApiAccountsByAccountIdUpdateJsonResponses,
  PutApiAccountsByAccountIdUpdateJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutApiAccountsByAccountIdUpdateJsonResponses,
    PutApiAccountsByAccountIdUpdateJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/accounts/{account-id}/update.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Submit AT communication
 *
 * Communicates the account's series to the Portuguese Tax Authority (AT).
 */
export const postApiV3AccountsAtCommunicationJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiV3AccountsAtCommunicationJsonData, ThrowOnError>,
): RequestResult<
  PostApiV3AccountsAtCommunicationJsonResponses,
  PostApiV3AccountsAtCommunicationJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiV3AccountsAtCommunicationJsonResponses,
    PostApiV3AccountsAtCommunicationJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/accounts/at_communication.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a client's balance
 *
 * Returns the treasury balance of a specific client.
 */
export const getApiV3ClientsByClientIdBalanceJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV3ClientsByClientIdBalanceJsonData, ThrowOnError>,
): RequestResult<
  GetApiV3ClientsByClientIdBalanceJsonResponses,
  GetApiV3ClientsByClientIdBalanceJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiV3ClientsByClientIdBalanceJsonResponses,
    GetApiV3ClientsByClientIdBalanceJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/clients/{client-id}/balance.json",
    ...options,
  });

/**
 * Update a client's initial balance
 *
 * Updates the initial treasury balance of a specific client.
 */
export const putApiV3ClientsByClientIdInitialBalanceJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PutApiV3ClientsByClientIdInitialBalanceJsonData,
    ThrowOnError
  >,
): RequestResult<
  PutApiV3ClientsByClientIdInitialBalanceJsonResponses,
  PutApiV3ClientsByClientIdInitialBalanceJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutApiV3ClientsByClientIdInitialBalanceJsonResponses,
    PutApiV3ClientsByClientIdInitialBalanceJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/clients/{client-id}/initial_balance.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List a client's regularizations
 *
 * Returns the list of a client's treasury regularizations.
 */
export const getApiV3ClientsByClientIdRegularizationJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetApiV3ClientsByClientIdRegularizationJsonData,
    ThrowOnError
  >,
): RequestResult<
  GetApiV3ClientsByClientIdRegularizationJsonResponses,
  GetApiV3ClientsByClientIdRegularizationJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiV3ClientsByClientIdRegularizationJsonResponses,
    GetApiV3ClientsByClientIdRegularizationJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/clients/{client-id}/regularization.json",
    ...options,
  });

/**
 * Create a regularization
 *
 * Creates a new treasury regularization for a client.
 */
export const postApiV3ClientsByClientIdRegularizationJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PostApiV3ClientsByClientIdRegularizationJsonData,
    ThrowOnError
  >,
): RequestResult<
  PostApiV3ClientsByClientIdRegularizationJsonResponses,
  PostApiV3ClientsByClientIdRegularizationJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiV3ClientsByClientIdRegularizationJsonResponses,
    PostApiV3ClientsByClientIdRegularizationJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/clients/{client-id}/regularization.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a regularization
 *
 * Deletes a client's treasury regularization.
 */
export const deleteApiV3ClientsByClientIdRegularizationByIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteApiV3ClientsByClientIdRegularizationByIdJsonData,
    ThrowOnError
  >,
): RequestResult<
  DeleteApiV3ClientsByClientIdRegularizationByIdJsonResponses,
  DeleteApiV3ClientsByClientIdRegularizationByIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteApiV3ClientsByClientIdRegularizationByIdJsonResponses,
    DeleteApiV3ClientsByClientIdRegularizationByIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/clients/{client-id}/regularization/{id}.json",
    ...options,
  });

/**
 * Create a treasury movement
 *
 * Creates a new treasury movement for a client.
 */
export const postApiV3ClientsByClientIdTreasuryMovementsJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PostApiV3ClientsByClientIdTreasuryMovementsJsonData,
    ThrowOnError
  >,
): RequestResult<
  PostApiV3ClientsByClientIdTreasuryMovementsJsonResponses,
  PostApiV3ClientsByClientIdTreasuryMovementsJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiV3ClientsByClientIdTreasuryMovementsJsonResponses,
    PostApiV3ClientsByClientIdTreasuryMovementsJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/clients/{client-id}/treasury_movements.json",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a treasury movement
 *
 * Deletes a client's treasury movement.
 */
export const deleteApiV3ClientsByClientIdTreasuryMovementsByIdJson = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonData,
    ThrowOnError
  >,
): RequestResult<
  DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonResponses,
  DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonResponses,
    DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "api_key",
        type: "apiKey",
      },
    ],
    url: "/api/v3/clients/{client-id}/treasury_movements/{id}.json",
    ...options,
  });
