// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import type { BaseHttpRequest } from "./core/BaseHttpRequest";
import type { $OpenApiTs } from "./types.gen";

export class InvoicesService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * Send document by email
   * @returns unknown The email was sent successfully.
   * @throws ApiError
   */
  public putByDocumentTypeByDocumentIdEmailDocumentJson(
    data: $OpenApiTs["/{document-type}/{document-id}/email-document.json"]["put"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/{document-type}/{document-id}/email-document.json"]["put"]["res"][200]
  > {
    const { apiKey, documentType, documentId, requestBody } = data;
    return this.httpRequest.request({
      method: "PUT",
      url: "/{document-type}/{document-id}/email-document.json",
      path: {
        "document-type": documentType,
        "document-id": documentId,
      },
      query: {
        api_key: apiKey,
      },
      body: requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. The supplied document-id doesn’t match any existing document.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }

  /**
   * Get Invoice
   * @returns Invoice The invoice was returned successfully.
   * @throws ApiError
   */
  public getByDocumentTypeByDocumentIdJson(
    data: $OpenApiTs["/{document-type}/{document-id}.json"]["get"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/{document-type}/{document-id}.json"]["get"]["res"][200]
  > {
    const { apiKey, documentType, documentId } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/{document-type}/{document-id}.json",
      path: {
        "document-type": documentType,
        "document-id": documentId,
      },
      query: {
        api_key: apiKey,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No invoice matches the supplied document-id.",
      },
    });
  }

  /**
   * Generate PDF
   * @returns unknown The request has been successfully processed.
   * @throws ApiError
   */
  public getApiPdfByDocumentIdJson(
    data: $OpenApiTs["/api/pdf/{document-id}.json"]["get"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/api/pdf/{document-id}.json"]["get"]["res"][200]
  > {
    const { apiKey, documentId, secondCopy } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/api/pdf/{document-id}.json",
      path: {
        "document-id": documentId,
      },
      query: {
        api_key: apiKey,
        second_copy: secondCopy,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No document matches the supplied document-id.",
        422: "Not acceptable. The document-id provided is in an invalid state.",
      },
    });
  }

  /**
   * List all invoices
   * @returns unknown Invoices were returned successfully.
   * @throws ApiError
   */
  public getInvoicesJson(
    data: $OpenApiTs["/invoices.json"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/invoices.json"]["get"]["res"][200]> {
    const {
      apiKey,
      typeArray,
      statusArray,
      nonArchived,
      page,
      perPage,
      text,
      dateFrom,
      dateTo,
      dueDateFrom,
      dueDateTo,
      totalBeforeTaxesFrom,
      totalBeforeTaxesTo,
      archived,
      reference,
    } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/invoices.json",
      query: {
        api_key: apiKey,
        text,
        "type[]": typeArray,
        "status[]": statusArray,
        "date[from]": dateFrom,
        "date[to]": dateTo,
        "due_date[from]": dueDateFrom,
        "due_date[to]": dueDateTo,
        "total_before_taxes[from]": totalBeforeTaxesFrom,
        "total_before_taxes[to]": totalBeforeTaxesTo,
        non_archived: nonArchived,
        archived,
        page,
        per_page: perPage,
        reference,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
      },
    });
  }

  /**
   * Create an invoice_receipts
   * @returns unknown Invoice was created successfully.
   * @throws ApiError
   */
  public postInvoiceReceiptsJson(
    data: $OpenApiTs["/invoice_receipts.json"]["post"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/invoice_receipts.json"]["post"]["res"][201]
  > {
    const { apiKey, requestBody } = data;
    return this.httpRequest.request({
      method: "POST",
      url: "/invoice_receipts.json",
      query: {
        api_key: apiKey,
      },
      body: requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        409: "Conflict. There’s an ongoing document creation with the provided UID.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }
}

export class ClientsService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * List all clients
   * Retrieves a list of clients.
   * @returns ClientsResponse Clients List all
   * @throws ApiError
   */
  public getClientsJson(
    data: $OpenApiTs["/clients.json"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/clients.json"]["get"]["res"][200]> {
    const { apiKey, page, perPage } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/clients.json",
      query: {
        api_key: apiKey,
        page,
        per_page: perPage,
      },
      errors: {
        401: "ACCESS DENIED",
      },
    });
  }

  /**
   * Create a new client
   * Creates a new client.
   * @returns ClientResponse SUCCESS
   * @throws ApiError
   */
  public postClientsJson(
    data: $OpenApiTs["/clients.json"]["post"]["req"],
  ): CancelablePromise<$OpenApiTs["/clients.json"]["post"]["res"][201]> {
    const { apiKey, requestBody } = data;
    return this.httpRequest.request({
      method: "POST",
      url: "/clients.json",
      query: {
        api_key: apiKey,
      },
      body: requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Get a client by ID
   * Retrieves a client by their ID.
   * @returns ClientResponse Clients Get
   * @throws ApiError
   */
  public getClientsByClientIdJson(
    data: $OpenApiTs["/clients/{client-id}.json"]["get"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/clients/{client-id}.json"]["get"]["res"][200]
  > {
    const { apiKey, clientId } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/clients/{client-id}.json",
      path: {
        "client-id": clientId,
      },
      query: {
        api_key: apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * Update a client by ID
   * Updates a client's information by their ID.
   * @returns unknown SUCCESS
   * @throws ApiError
   */
  public putClientsByClientIdJson(
    data: $OpenApiTs["/clients/{client-id}.json"]["put"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/clients/{client-id}.json"]["put"]["res"][200]
  > {
    const { apiKey, clientId, requestBody } = data;
    return this.httpRequest.request({
      method: "PUT",
      url: "/clients/{client-id}.json",
      path: {
        "client-id": clientId,
      },
      query: {
        api_key: apiKey,
      },
      body: requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Find client by name
   * Retrieves a client by their name.
   * @returns ClientResponse Client Get
   * @throws ApiError
   */
  public getClientsFindByNameJson(
    data: $OpenApiTs["/clients/find-by-name.json"]["get"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/clients/find-by-name.json"]["get"]["res"][200]
  > {
    const { apiKey, clientName } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/clients/find-by-name.json",
      query: {
        api_key: apiKey,
        client_name: clientName,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * Find client by code
   * Retrieves a client by their code.
   * @returns ClientResponse Client Get
   * @throws ApiError
   */
  public getClientsFindByCodeJson(
    data: $OpenApiTs["/clients/find-by-code.json"]["get"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/clients/find-by-code.json"]["get"]["res"][200]
  > {
    const { apiKey, clientCode } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/clients/find-by-code.json",
      query: {
        api_key: apiKey,
        client_code: clientCode,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * List invoices for a client
   * Retrieves a list of invoices for a specific client.
   * @returns InvoicesResponse The client’s invoices
   * @throws ApiError
   */
  public postClientsByClientIdInvoicesJson(
    data: $OpenApiTs["/clients/{client-id}/invoices.json"]["post"]["req"],
  ): CancelablePromise<
    $OpenApiTs["/clients/{client-id}/invoices.json"]["post"]["res"][200]
  > {
    const { apiKey, clientId, requestBody, page, perPage } = data;
    return this.httpRequest.request({
      method: "POST",
      url: "/clients/{client-id}/invoices.json",
      path: {
        "client-id": clientId,
      },
      query: {
        api_key: apiKey,
        page,
        per_page: perPage,
      },
      body: requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }
}

export class SaftService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * Export SAF-T
   * Generates the SAF-T file for a specific date (month and year). The first response given will have a HTTP 202 code, meaning the generation was started. You need to keep requesting until you get a response with HTTP status code 200, and the URL to download the file in the message body.
   * @returns unknown The link to download your SAF-T file.
   * @throws ApiError
   */
  public getApiExportSaftJson(
    data: $OpenApiTs["/api/export_saft.json"]["get"]["req"],
  ): CancelablePromise<$OpenApiTs["/api/export_saft.json"]["get"]["res"][200]> {
    const { apiKey, month, year } = data;
    return this.httpRequest.request({
      method: "GET",
      url: "/api/export_saft.json",
      query: {
        api_key: apiKey,
        month,
        year,
      },
      errors: {
        422: "Some parameters sent in the request were not valid.",
        500: "The SAF-T file generation failed.",
      },
    });
  }
}
