// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import type { BaseHttpRequest } from "./core/BaseHttpRequest";
import type {
  PutInvoiceReceiptsByDocumentIdEmailDocumentJsonData,
  PutInvoiceReceiptsByDocumentIdEmailDocumentJsonResponse,
  PutInvoiceReceiptsByDocumentIdChangeStateJsonData,
  PutInvoiceReceiptsByDocumentIdChangeStateJsonResponse,
  GetInvoiceReceiptsByDocumentIdJsonData,
  GetInvoiceReceiptsByDocumentIdJsonResponse,
  GetApiPdfByDocumentIdJsonData,
  GetApiPdfByDocumentIdJsonResponse,
  PostInvoiceReceiptsJsonData,
  PostInvoiceReceiptsJsonResponse,
  GetInvoicesJsonData,
  GetInvoicesJsonResponse,
  PostInvoicesJsonData,
  PostInvoicesJsonResponse,
  GetInvoicesByDocumentIdJsonData,
  GetInvoicesByDocumentIdJsonResponse,
  PutInvoicesByDocumentIdJsonData,
  PutInvoicesByDocumentIdJsonResponse,
  PutInvoicesByDocumentIdChangeStateJsonData,
  PutInvoicesByDocumentIdChangeStateJsonResponse,
  GetDocumentByDocumentIdRelatedDocumentsJsonData,
  GetDocumentByDocumentIdRelatedDocumentsJsonResponse,
  PostDocumentsByDocumentIdPartialPaymentsJsonData,
  PostDocumentsByDocumentIdPartialPaymentsJsonResponse,
  GetClientsJsonData,
  GetClientsJsonResponse,
  PostClientsJsonData,
  PostClientsJsonResponse,
  GetClientsByClientIdJsonData,
  GetClientsByClientIdJsonResponse,
  PutClientsByClientIdJsonData,
  PutClientsByClientIdJsonResponse,
  GetClientsFindByNameJsonData,
  GetClientsFindByNameJsonResponse,
  GetClientsFindByCodeJsonData,
  GetClientsFindByCodeJsonResponse,
  PostClientsByClientIdInvoicesJsonData,
  PostClientsByClientIdInvoicesJsonResponse,
  GetApiExportSaftJsonData,
  GetApiExportSaftJsonResponse,
  GetTaxesJsonData,
  GetTaxesJsonResponse,
  PostTaxesJsonData,
  PostTaxesJsonResponse,
  GetTaxesByTaxIdJsonData,
  GetTaxesByTaxIdJsonResponse,
  PutTaxesByTaxIdJsonData,
  PutTaxesByTaxIdJsonResponse,
  DeleteTaxesByTaxIdJsonData,
  DeleteTaxesByTaxIdJsonResponse,
  GetItemsJsonData,
  GetItemsJsonResponse,
  PostItemsJsonData,
  PostItemsJsonResponse,
  GetItemsByItemIdJsonData,
  GetItemsByItemIdJsonResponse,
  PutItemsByItemIdJsonData,
  PutItemsByItemIdJsonResponse,
  DeleteItemsByItemIdJsonData,
  DeleteItemsByItemIdJsonResponse,
  GetGuidesJsonData,
  GetGuidesJsonResponse,
  GetApiQrCodesByDocumentIdJsonData,
  GetApiQrCodesByDocumentIdJsonResponse,
  PostByGuidesTypeJsonData,
  PostByGuidesTypeJsonResponse,
  GetByGuidesTypeByDocumentIdJsonData,
  GetByGuidesTypeByDocumentIdJsonResponse,
  PutByGuidesTypeByDocumentIdJsonData,
  PutByGuidesTypeByDocumentIdJsonResponse,
  PutByGuidesTypeByDocumentIdChangeStateJsonData,
  PutByGuidesTypeByDocumentIdChangeStateJsonResponse,
  PutByGuidesTypeByDocumentIdEmailDocumentJsonData,
  PutByGuidesTypeByDocumentIdEmailDocumentJsonResponse,
  GetEstimatesJsonData,
  GetEstimatesJsonResponse,
  PostByEstimatesTypeJsonData,
  PostByEstimatesTypeJsonResponse,
  GetByEstimatesTypeByDocumentIdJsonData,
  GetByEstimatesTypeByDocumentIdJsonResponse,
  PutByEstimatesTypeByDocumentIdJsonData,
  PutByEstimatesTypeByDocumentIdJsonResponse,
  PutByEstimatesTypeByDocumentIdChangeStateJsonData,
  PutByEstimatesTypeByDocumentIdChangeStateJsonResponse,
  PutByEstimatesTypeByDocumentIdEmailDocumentJsonData,
  PutByEstimatesTypeByDocumentIdEmailDocumentJsonResponse,
} from "./types.gen";

export class InvoicesReceiptsService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * Send document by email
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown The email was sent successfully.
   * @throws ApiError
   */
  public putInvoiceReceiptsByDocumentIdEmailDocumentJson(
    data: PutInvoiceReceiptsByDocumentIdEmailDocumentJsonData,
  ): CancelablePromise<PutInvoiceReceiptsByDocumentIdEmailDocumentJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/invoice_receipts/{document-id}/email-document.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. The supplied document-id doesn’t match any existing document.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }

  /**
   * Change the state of a document
   * Changes the state of an invoice, simplified_invoice, invoice_receipt, credit_note, or debit_note.
   * @param data The data for the request.
   * @param data.documentId The unique identifier of the document.
   * @param data.apiKey Your API key.
   * @param data.requestBody
   * @returns unknown Successfully changed the document state.
   * @throws ApiError
   */
  public putInvoiceReceiptsByDocumentIdChangeStateJson(
    data: PutInvoiceReceiptsByDocumentIdChangeStateJsonData,
  ): CancelablePromise<PutInvoiceReceiptsByDocumentIdChangeStateJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/invoice_receipts/{document-id}/change-state.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        400: "Invalid request.",
      },
    });
  }

  /**
   * Get Invoice
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @returns Invoice The invoice was returned successfully.
   * @throws ApiError
   */
  public getInvoiceReceiptsByDocumentIdJson(
    data: GetInvoiceReceiptsByDocumentIdJsonData,
  ): CancelablePromise<GetInvoiceReceiptsByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/invoice_receipts/{document-id}.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No invoice matches the supplied document-id.",
      },
    });
  }

  /**
   * Generate PDF
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @param data.secondCopy
   * @returns unknown The request has been successfully processed.
   * @returns unknown The request will be processed. You need to keep requesting until you get a response with HTTP status code 200.
   * @throws ApiError
   */
  public getApiPdfByDocumentIdJson(
    data: GetApiPdfByDocumentIdJsonData,
  ): CancelablePromise<GetApiPdfByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/api/pdf/{document-id}.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
        second_copy: data.secondCopy,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No document matches the supplied document-id.",
        422: "Not acceptable. The document-id provided is in an invalid state.",
      },
    });
  }

  /**
   * Create an invoice_receipts
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.requestBody
   * @returns unknown Invoice was created successfully.
   * @throws ApiError
   */
  public postInvoiceReceiptsJson(
    data: PostInvoiceReceiptsJsonData,
  ): CancelablePromise<PostInvoiceReceiptsJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/invoice_receipts.json",
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        409: "Conflict. There’s an ongoing document creation with the provided UID.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }
}

export class InvoicesService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * List all invoices
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.typeArray
   * @param data.statusArray
   * @param data.nonArchived
   * @param data.page Page number to retrieve.
   * @param data.perPage Per_page number to retrieve.
   * @param data.text
   * @param data.dateFrom
   * @param data.dateTo
   * @param data.dueDateFrom
   * @param data.dueDateTo
   * @param data.totalBeforeTaxesFrom
   * @param data.totalBeforeTaxesTo
   * @param data.archived
   * @param data.reference
   * @returns InvoicesResponse The client’s invoices
   * @throws ApiError
   */
  public getInvoicesJson(
    data: GetInvoicesJsonData,
  ): CancelablePromise<GetInvoicesJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/invoices.json",
      query: {
        api_key: data.apiKey,
        text: data.text,
        "type[]": data.typeArray,
        "status[]": data.statusArray,
        "date[from]": data.dateFrom,
        "date[to]": data.dateTo,
        "due_date[from]": data.dueDateFrom,
        "due_date[to]": data.dueDateTo,
        "total_before_taxes[from]": data.totalBeforeTaxesFrom,
        "total_before_taxes[to]": data.totalBeforeTaxesTo,
        non_archived: data.nonArchived,
        archived: data.archived,
        page: data.page,
        per_page: data.perPage,
        reference: data.reference,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
      },
    });
  }

  /**
   * Create an invoice
   * Creates an invoice. Use the matching document-type endpoint for other documents (e.g. simplified_invoices, credit_notes, debit_notes).
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.requestBody
   * @returns InvoiceResponse Invoice was created successfully.
   * @throws ApiError
   */
  public postInvoicesJson(
    data: PostInvoicesJsonData,
  ): CancelablePromise<PostInvoicesJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/invoices.json",
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        409: "Conflict. There’s an ongoing document creation with the provided UID.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }

  /**
   * Get an invoice
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @returns InvoiceResponse The invoice was returned successfully.
   * @throws ApiError
   */
  public getInvoicesByDocumentIdJson(
    data: GetInvoicesByDocumentIdJsonData,
  ): CancelablePromise<GetInvoicesByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/invoices/{document-id}.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No invoice matches the supplied document-id.",
      },
    });
  }

  /**
   * Update an invoice
   * Updates a draft invoice. Only invoices in the draft state can be updated.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown Invoice was updated successfully.
   * @throws ApiError
   */
  public putInvoicesByDocumentIdJson(
    data: PutInvoicesByDocumentIdJsonData,
  ): CancelablePromise<PutInvoicesByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/invoices/{document-id}.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No invoice matches the supplied document-id.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }

  /**
   * Change the state of an invoice
   * Changes the state of an invoice (finalized, deleted, canceled, settled).
   * @param data The data for the request.
   * @param data.documentId The unique identifier of the document.
   * @param data.apiKey
   * @param data.requestBody
   * @returns unknown Successfully changed the document state.
   * @throws ApiError
   */
  public putInvoicesByDocumentIdChangeStateJson(
    data: PutInvoicesByDocumentIdChangeStateJsonData,
  ): CancelablePromise<PutInvoicesByDocumentIdChangeStateJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/invoices/{document-id}/change-state.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. The supplied document-id doesn’t match any existing document.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }

  /**
   * List related documents
   * Returns the documents (receipts, credit notes, debit notes) related to the given document.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @returns InvoicesResponse The related documents.
   * @throws ApiError
   */
  public getDocumentByDocumentIdRelatedDocumentsJson(
    data: GetDocumentByDocumentIdRelatedDocumentsJsonData,
  ): CancelablePromise<GetDocumentByDocumentIdRelatedDocumentsJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/document/{document-id}/related_documents.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No document matches the supplied document-id.",
      },
    });
  }

  /**
   * Generate a payment (receipt)
   * Generates a receipt for a (partial) payment of an invoice or simplified invoice.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown The receipt was created successfully.
   * @throws ApiError
   */
  public postDocumentsByDocumentIdPartialPaymentsJson(
    data: PostDocumentsByDocumentIdPartialPaymentsJsonData,
  ): CancelablePromise<PostDocumentsByDocumentIdPartialPaymentsJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/documents/{document-id}/partial_payments.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No document matches the supplied document-id.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }
}

export class ClientsService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * List all clients
   * Retrieves a list of clients.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.page Page number to retrieve.
   * @param data.perPage Number of clients per page.
   * @returns ClientsResponse Clients List all
   * @throws ApiError
   */
  public getClientsJson(
    data: GetClientsJsonData,
  ): CancelablePromise<GetClientsJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/clients.json",
      query: {
        api_key: data.apiKey,
        page: data.page,
        per_page: data.perPage,
      },
      errors: {
        401: "ACCESS DENIED",
      },
    });
  }

  /**
   * Create a new client
   * Creates a new client.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.requestBody
   * @returns ClientResponse SUCCESS
   * @throws ApiError
   */
  public postClientsJson(
    data: PostClientsJsonData,
  ): CancelablePromise<PostClientsJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/clients.json",
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Get a client by ID
   * Retrieves a client by their ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.clientId The ID of the client you want to get.
   * @returns ClientResponse Clients Get
   * @throws ApiError
   */
  public getClientsByClientIdJson(
    data: GetClientsByClientIdJsonData,
  ): CancelablePromise<GetClientsByClientIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/clients/{client-id}.json",
      path: {
        "client-id": data.clientId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * Update a client by ID
   * Updates a client's information by their ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.clientId The ID of the client to be updated.
   * @param data.requestBody
   * @returns unknown SUCCESS
   * @throws ApiError
   */
  public putClientsByClientIdJson(
    data: PutClientsByClientIdJsonData,
  ): CancelablePromise<PutClientsByClientIdJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/clients/{client-id}.json",
      path: {
        "client-id": data.clientId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Find client by name
   * Retrieves a client by their name.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.clientName
   * @returns ClientResponse Client Get
   * @throws ApiError
   */
  public getClientsFindByNameJson(
    data: GetClientsFindByNameJsonData,
  ): CancelablePromise<GetClientsFindByNameJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/clients/find-by-name.json",
      query: {
        api_key: data.apiKey,
        client_name: data.clientName,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * Find client by code
   * Retrieves a client by their code.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.clientCode The client code you want to search.
   * @returns ClientResponse Client Get
   * @throws ApiError
   */
  public getClientsFindByCodeJson(
    data: GetClientsFindByCodeJsonData,
  ): CancelablePromise<GetClientsFindByCodeJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/clients/find-by-code.json",
      query: {
        api_key: data.apiKey,
        client_code: data.clientCode,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * List invoices for a client
   * Retrieves a list of invoices for a specific client.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.clientId Filter invoices for this client.
   * @param data.requestBody
   * @param data.page You can ask for a specific page of invoices. Defaults to 1.
   * @param data.perPage You can specify how many results you want to fetch. Defaults to 10 or value defined in account settings (10, 20 or 30).
   * @returns InvoicesResponse The client’s invoices
   * @throws ApiError
   */
  public postClientsByClientIdInvoicesJson(
    data: PostClientsByClientIdInvoicesJsonData,
  ): CancelablePromise<PostClientsByClientIdInvoicesJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/clients/{client-id}/invoices.json",
      path: {
        "client-id": data.clientId,
      },
      query: {
        api_key: data.apiKey,
        page: data.page,
        per_page: data.perPage,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }
}

export class SaftService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * Export SAF-T
   * Generates the SAF-T file for a specific date (month and years). The first response given will have a HTTP 202 code, meaning the generation was started. You need to keep requesting until you get a response with HTTP status code 200, and the URL to download the file in the message body.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.month
   * @param data.years
   * @returns unknown The link to download your SAF-T file.
   * @returns unknown Your SAF-T file is being generated. You need to keep requesting until you get a response with HTTP status code 200.
   * @throws ApiError
   */
  public getApiExportSaftJson(
    data: GetApiExportSaftJsonData,
  ): CancelablePromise<GetApiExportSaftJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/api/export_saft.json",
      query: {
        api_key: data.apiKey,
        month: data.month,
        years: data.years,
      },
      errors: {
        422: "Some parameters sent in the request were not valid.",
        500: "The SAF-T file generation failed.",
      },
    });
  }
}

export class TaxesService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * List all taxes
   * Retrieves a list of taxes.
   * @param data The data for the request.
   * @param data.apiKey
   * @returns TaxesResponse Taxes List all
   * @throws ApiError
   */
  public getTaxesJson(
    data: GetTaxesJsonData,
  ): CancelablePromise<GetTaxesJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/taxes.json",
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
      },
    });
  }

  /**
   * Create a new tax
   * Creates a new tax.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.requestBody
   * @returns TaxResponse SUCCESS
   * @throws ApiError
   */
  public postTaxesJson(
    data: PostTaxesJsonData,
  ): CancelablePromise<PostTaxesJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/taxes.json",
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Get a tax by ID
   * Retrieves a tax by their ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.taxId The ID of the tax you want to get.
   * @returns TaxResponse Tax Get
   * @throws ApiError
   */
  public getTaxesByTaxIdJson(
    data: GetTaxesByTaxIdJsonData,
  ): CancelablePromise<GetTaxesByTaxIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/taxes/{tax-id}.json",
      path: {
        "tax-id": data.taxId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * Update a tax by ID
   * Updates a tax's information by its ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.taxId The ID of the tax to be updated.
   * @param data.requestBody
   * @returns TaxResponse SUCCESS
   * @throws ApiError
   */
  public putTaxesByTaxIdJson(
    data: PutTaxesByTaxIdJsonData,
  ): CancelablePromise<PutTaxesByTaxIdJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/taxes/{tax-id}.json",
      path: {
        "tax-id": data.taxId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Delete a tax by ID
   * Deletes a tax by its ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.taxId The ID of the tax to be deleted.
   * @returns unknown SUCCESS
   * @throws ApiError
   */
  public deleteTaxesByTaxIdJson(
    data: DeleteTaxesByTaxIdJsonData,
  ): CancelablePromise<DeleteTaxesByTaxIdJsonResponse> {
    return this.httpRequest.request({
      method: "DELETE",
      url: "/taxes/{tax-id}.json",
      path: {
        "tax-id": data.taxId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }
}

export class ItemsService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * List all items
   * Retrieves a list of items.
   * @param data The data for the request.
   * @param data.apiKey
   * @returns ItemsResponse Items List all
   * @throws ApiError
   */
  public getItemsJson(
    data: GetItemsJsonData,
  ): CancelablePromise<GetItemsJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/items.json",
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
      },
    });
  }

  /**
   * Create a new item
   * Creates a new item.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.requestBody
   * @returns ItemResponse SUCCESS
   * @throws ApiError
   */
  public postItemsJson(
    data: PostItemsJsonData,
  ): CancelablePromise<PostItemsJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/items.json",
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Get a item by ID
   * Retrieves a item by their ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.itemId The ID of the item you want to get.
   * @returns ItemResponse Item Get
   * @throws ApiError
   */
  public getItemsByItemIdJson(
    data: GetItemsByItemIdJsonData,
  ): CancelablePromise<GetItemsByItemIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/items/{item-id}.json",
      path: {
        "item-id": data.itemId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }

  /**
   * Update an item by ID
   * Updates an item's information by its ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.itemId The ID of the item to be updated.
   * @param data.requestBody
   * @returns ItemResponse SUCCESS
   * @throws ApiError
   */
  public putItemsByItemIdJson(
    data: PutItemsByItemIdJsonData,
  ): CancelablePromise<PutItemsByItemIdJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/items/{item-id}.json",
      path: {
        "item-id": data.itemId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
        422: "UNPROCESSABLE ENTITY",
      },
    });
  }

  /**
   * Delete an item by ID
   * Deletes an item by its ID.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.itemId The ID of the item to be deleted.
   * @returns unknown SUCCESS
   * @throws ApiError
   */
  public deleteItemsByItemIdJson(
    data: DeleteItemsByItemIdJsonData,
  ): CancelablePromise<DeleteItemsByItemIdJsonResponse> {
    return this.httpRequest.request({
      method: "DELETE",
      url: "/items/{item-id}.json",
      path: {
        "item-id": data.itemId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "ACCESS DENIED",
        404: "NOT FOUND",
      },
    });
  }
}

export class GuidesService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * List all guides
   * Retrieves a list of guides (shippings, transports and devolutions).
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.page Page number to retrieve.
   * @param data.perPage Per_page number to retrieve.
   * @param data.text
   * @param data.typeArray
   * @param data.statusArray
   * @param data.dateFrom
   * @param data.dateTo
   * @param data.nonArchived
   * @param data.archived
   * @returns GuidesResponse The list of guides.
   * @throws ApiError
   */
  public getGuidesJson(
    data: GetGuidesJsonData,
  ): CancelablePromise<GetGuidesJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/guides.json",
      query: {
        api_key: data.apiKey,
        text: data.text,
        "type[]": data.typeArray,
        "status[]": data.statusArray,
        "date[from]": data.dateFrom,
        "date[to]": data.dateTo,
        non_archived: data.nonArchived,
        archived: data.archived,
        page: data.page,
        per_page: data.perPage,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
      },
    });
  }

  /**
   * Get the QR code of a document
   * Returns the QR code image URL for a finalized document.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.documentId
   * @returns unknown The QR code was returned successfully.
   * @throws ApiError
   */
  public getApiQrCodesByDocumentIdJson(
    data: GetApiQrCodesByDocumentIdJsonData,
  ): CancelablePromise<GetApiQrCodesByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/api/qr_codes/{document-id}.json",
      path: {
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No document matches the supplied document-id.",
      },
    });
  }

  /**
   * Create a guide
   * Creates a guide of the given type (shippings, transports or devolutions).
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.guidesType The type of guide to create.
   * @param data.requestBody
   * @returns GuideResponse Guide was created successfully.
   * @throws ApiError
   */
  public postByGuidesTypeJson(
    data: PostByGuidesTypeJsonData,
  ): CancelablePromise<PostByGuidesTypeJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/{guides-type}.json",
      path: {
        "guides-type": data.guidesType,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }

  /**
   * Get a guide
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.guidesType The type of guide.
   * @param data.documentId
   * @returns GuideResponse The guide was returned successfully.
   * @throws ApiError
   */
  public getByGuidesTypeByDocumentIdJson(
    data: GetByGuidesTypeByDocumentIdJsonData,
  ): CancelablePromise<GetByGuidesTypeByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/{guides-type}/{document-id}.json",
      path: {
        "guides-type": data.guidesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No guide matches the supplied document-id.",
      },
    });
  }

  /**
   * Update a guide
   * Updates a draft guide. Only guides in the draft state can be updated.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.guidesType The type of guide.
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown Guide was updated successfully.
   * @throws ApiError
   */
  public putByGuidesTypeByDocumentIdJson(
    data: PutByGuidesTypeByDocumentIdJsonData,
  ): CancelablePromise<PutByGuidesTypeByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/{guides-type}/{document-id}.json",
      path: {
        "guides-type": data.guidesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No guide matches the supplied document-id.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }

  /**
   * Change the state of a guide
   * Changes the state of a guide (finalized, deleted, canceled).
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.guidesType The type of guide.
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown Successfully changed the guide state.
   * @throws ApiError
   */
  public putByGuidesTypeByDocumentIdChangeStateJson(
    data: PutByGuidesTypeByDocumentIdChangeStateJsonData,
  ): CancelablePromise<PutByGuidesTypeByDocumentIdChangeStateJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/{guides-type}/{document-id}/change-state.json",
      path: {
        "guides-type": data.guidesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. The supplied document-id doesn’t match any existing document.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }

  /**
   * Send guide by email
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.guidesType The type of guide.
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown The email was sent successfully.
   * @throws ApiError
   */
  public putByGuidesTypeByDocumentIdEmailDocumentJson(
    data: PutByGuidesTypeByDocumentIdEmailDocumentJsonData,
  ): CancelablePromise<PutByGuidesTypeByDocumentIdEmailDocumentJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/{guides-type}/{document-id}/email-document.json",
      path: {
        "guides-type": data.guidesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. The supplied document-id doesn’t match any existing document.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }
}

export class EstimatesService {
  constructor(public readonly httpRequest: BaseHttpRequest) {}

  /**
   * List all estimates
   * Retrieves a list of estimates (quotes, proformas and fees notes).
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.page Page number to retrieve.
   * @param data.perPage Per_page number to retrieve.
   * @param data.text
   * @param data.typeArray
   * @param data.statusArray
   * @param data.dateFrom
   * @param data.dateTo
   * @param data.nonArchived
   * @param data.archived
   * @returns EstimatesResponse The list of estimates.
   * @throws ApiError
   */
  public getEstimatesJson(
    data: GetEstimatesJsonData,
  ): CancelablePromise<GetEstimatesJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/estimates.json",
      query: {
        api_key: data.apiKey,
        text: data.text,
        "type[]": data.typeArray,
        "status[]": data.statusArray,
        "date[from]": data.dateFrom,
        "date[to]": data.dateTo,
        non_archived: data.nonArchived,
        archived: data.archived,
        page: data.page,
        per_page: data.perPage,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
      },
    });
  }

  /**
   * Create an estimate
   * Creates an estimate of the given type (quotes, proformas or fees_notes).
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.estimatesType The type of estimate to create.
   * @param data.requestBody
   * @returns EstimateResponse Estimate was created successfully.
   * @throws ApiError
   */
  public postByEstimatesTypeJson(
    data: PostByEstimatesTypeJsonData,
  ): CancelablePromise<PostByEstimatesTypeJsonResponse> {
    return this.httpRequest.request({
      method: "POST",
      url: "/{estimates-type}.json",
      path: {
        "estimates-type": data.estimatesType,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }

  /**
   * Get an estimate
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.estimatesType The type of estimate.
   * @param data.documentId
   * @returns EstimateResponse The estimate was returned successfully.
   * @throws ApiError
   */
  public getByEstimatesTypeByDocumentIdJson(
    data: GetByEstimatesTypeByDocumentIdJsonData,
  ): CancelablePromise<GetByEstimatesTypeByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "GET",
      url: "/{estimates-type}/{document-id}.json",
      path: {
        "estimates-type": data.estimatesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No estimate matches the supplied document-id.",
      },
    });
  }

  /**
   * Update an estimate
   * Updates a draft estimate. Only estimates in the draft state can be updated.
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.estimatesType The type of estimate.
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown Estimate was updated successfully.
   * @throws ApiError
   */
  public putByEstimatesTypeByDocumentIdJson(
    data: PutByEstimatesTypeByDocumentIdJsonData,
  ): CancelablePromise<PutByEstimatesTypeByDocumentIdJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/{estimates-type}/{document-id}.json",
      path: {
        "estimates-type": data.estimatesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. No estimate matches the supplied document-id.",
        422: "Unprocessable Entity. Some parameters were incorrect.",
      },
    });
  }

  /**
   * Change the state of an estimate
   * Changes the state of an estimate (finalized, deleted, accepted, refused, canceled).
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.estimatesType The type of estimate.
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown Successfully changed the estimate state.
   * @throws ApiError
   */
  public putByEstimatesTypeByDocumentIdChangeStateJson(
    data: PutByEstimatesTypeByDocumentIdChangeStateJsonData,
  ): CancelablePromise<PutByEstimatesTypeByDocumentIdChangeStateJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/{estimates-type}/{document-id}/change-state.json",
      path: {
        "estimates-type": data.estimatesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. The supplied document-id doesn’t match any existing document.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }

  /**
   * Send estimate by email
   * @param data The data for the request.
   * @param data.apiKey
   * @param data.estimatesType The type of estimate.
   * @param data.documentId
   * @param data.requestBody
   * @returns unknown The email was sent successfully.
   * @throws ApiError
   */
  public putByEstimatesTypeByDocumentIdEmailDocumentJson(
    data: PutByEstimatesTypeByDocumentIdEmailDocumentJsonData,
  ): CancelablePromise<PutByEstimatesTypeByDocumentIdEmailDocumentJsonResponse> {
    return this.httpRequest.request({
      method: "PUT",
      url: "/{estimates-type}/{document-id}/email-document.json",
      path: {
        "estimates-type": data.estimatesType,
        "document-id": data.documentId,
      },
      query: {
        api_key: data.apiKey,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        401: "Access denied. The API Key parameter is missing or is incorrectly entered.",
        404: "Not found. The supplied document-id doesn’t match any existing document.",
        422: "Unprocessable Entity. Some parameters sent were incorrect.",
      },
    });
  }
}
