// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://{account_name}.app.invoicexpress.com" | (string & {});
};

export type Tax = {
  id?: number;
  name: string;
  /**
   * Tax rate as returned by the API (a string, e.g. "23.0").
   */
  value: string;
  region?: string;
  code?: string;
  default_tax?: number;
};

export type TaxResponse = {
  tax?: Tax;
};

export type TaxesResponse = {
  taxes: Array<Tax>;
};

export type Item = {
  name: string;
  description?: string;
  unit_price: number;
  unit?: string;
  quantity: number;
  tax?: {
    id?: number;
    name?: string;
    value?: number;
  };
  discount?: number;
  subtotal?: number;
  tax_amount?: number;
  discount_amount?: number;
  total?: number;
};

export type ItemResponse = {
  item?: Item;
};

export type ItemsResponse = {
  items: Array<Item>;
};

export type MbReference = {
  entity: string;
  value: number;
  reference: string;
};

export type GlobalDiscount = {
  value_type: string;
  value: number;
};

export type Invoice = {
  id: number;
  status: string;
  archived?: boolean;
  type: string;
  sequence_number: string;
  inverted_sequence_number?: string;
  atcud?: string;
  sequence_id?: string;
  tax_exemption?: string;
  date: string;
  due_date: string;
  reference?: string;
  observations?: string;
  retention?: string;
  permalink?: string;
  saft_hash?: string;
  sum?: number;
  discount?: number;
  before_taxes?: number;
  taxes?: number;
  total: number;
  currency?: string;
  client: Client;
  items: Array<Item>;
  mb_reference?: MbReference;
  global_discount?: GlobalDiscount;
};

export type Client = {
  id: string;
  name: string;
  email?: string;
  address?: string;
  city?: string;
  postal_code?: string;
  fiscal_id?: string;
  website?: string;
  country?: string;
  phone?: string;
  fax?: string;
  preferred_contact?: {
    name?: string;
    email?: string;
    phone?: string;
  };
  observations?: string;
  open_account_link?: string;
  send_options?: string;
  payment_days?: string;
  tax_exemption_code?: string;
};

export type ClientsResponse = {
  clients: Array<Client>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type ClientResponse = {
  client?: Client;
};

export type InvoiceReceiptsRequest = {
  invoice_receipt: {
    date: string;
    due_date: string;
    status: string;
    sequence_id?: string;
    tax_exemption?: string;
    client?: {
      name: string;
    };
    items?: Array<Item>;
  };
};

export type ClientRequest = {
  client: {
    name: string;
    code?: string;
    email?: string;
    language?: string;
    address?: string;
    city?: string;
    postal_code?: string;
    country?: string;
    fiscal_id?: string;
    website?: string;
    phone?: string;
    fax?: string;
    preferred_contact?: {
      name?: string;
      email?: string;
      phone?: string;
    };
    observations?: string;
    send_options?: string;
  };
};

export type InvoicesResponse = {
  invoices: Array<Invoice>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type InvoiceResponse = {
  invoice: Invoice;
};

export type InvoiceRequest = {
  invoice: {
    /**
     * Document date in dd/mm/yyyy format.
     */
    date: string;
    /**
     * Due date in dd/mm/yyyy format.
     */
    due_date: string;
    reference?: string;
    observations?: string;
    /**
     * Retention percentage (0–99.99).
     */
    retention?: number;
    /**
     * Tax exemption code (required when an item has no tax).
     */
    tax_exemption?: string;
    tax_exemption_reason?: string;
    sequence_id?: string;
    manual_sequence_number?: string;
    currency_code?: string;
    /**
     * Exchange rate, required when currency_code differs from the account currency.
     */
    rate?: string;
    /**
     * Whether to generate a Multibanco reference for the document.
     */
    mb_reference?: boolean;
    /**
     * Source document id (e.g. when issuing a credit note).
     */
    owner_invoice_id?: number;
    client: {
      name: string;
      code?: string;
      email?: string;
      address?: string;
      city?: string;
      postal_code?: string;
      country?: string;
      fiscal_id?: string;
      website?: string;
      phone?: string;
      fax?: string;
      observations?: string;
    };
    items: Array<Item>;
    global_discount?: GlobalDiscount;
  };
  /**
   * Idempotency key to prevent duplicate document creation.
   */
  proprietary_uid?: string;
};

export type ItemRequest = {
  item: {
    name: string;
    description?: string;
    /**
     * Unit price, sent as a string (e.g. "50.0"). The /items.json endpoint rejects a numeric unit_price with a 422 "unit price is not valid" error.
     */
    unit_price: string;
    unit?: string;
    tax?: {
      name?: string;
    };
  };
};

export type TaxRequest = {
  tax: {
    name: string;
    /**
     * Tax rate, sent as a string (e.g. "23.0"). A numeric value is rejected by the /taxes.json endpoint with a 500.
     */
    value: string;
    /**
     * Required (e.g. "PT"); the API returns "region is empty" otherwise.
     */
    region: string;
    code?: string;
    default_tax?: boolean;
  };
};

export type Address = {
  detail?: string;
  city?: string;
  postal_code?: string;
  country?: string;
};

export type Guide = {
  id: number;
  status: string;
  archived?: boolean;
  /**
   * The guide type (Shipping, Transport or Devolution).
   */
  type: string;
  sequence_number?: string;
  inverted_sequence_number?: string;
  atcud?: string;
  tax_exemption?: string;
  date: string;
  /**
   * Loading date and time (dd/mm/yyyy HH:MM:SS).
   */
  loaded_at?: string;
  reference?: string;
  observations?: string;
  permalink?: string;
  saft_hash?: string;
  sum?: number;
  discount?: number;
  before_taxes?: number;
  taxes?: number;
  total?: number;
  currency?: string;
  address_from?: Address;
  address_to?: Address;
  client: Client;
  items: Array<Item>;
};

export type GuideBody = {
  /**
   * Document date in dd/mm/yyyy format.
   */
  date: string;
  /**
   * Loading date and time in dd/mm/yyyy HH:MM:SS format.
   */
  loaded_at?: string;
  reference?: string;
  observations?: string;
  /**
   * Tax exemption code (required when an item has no tax).
   */
  tax_exemption?: string;
  tax_exemption_reason?: string;
  sequence_id?: string;
  manual_sequence_number?: string;
  address_from?: Address;
  address_to?: Address;
  client: {
    name: string;
    code?: string;
    email?: string;
    address?: string;
    city?: string;
    postal_code?: string;
    country?: string;
    fiscal_id?: string;
    website?: string;
    phone?: string;
    fax?: string;
    observations?: string;
  };
  items: Array<Item>;
};

/**
 * Create/update payload. The root key must match the {guides-type} path
 * parameter: "shipping" for shippings, "transport" for transports,
 * "devolution" for devolutions.
 *
 */
export type GuideRequest =
  | {
      shipping: GuideBody;
    }
  | {
      transport: GuideBody;
    }
  | {
      devolution: GuideBody;
    };

/**
 * A single guide, wrapped under the key matching its type
 * ("shipping", "transport" or "devolution").
 *
 */
export type GuideResponse =
  | {
      shipping: Guide;
    }
  | {
      transport: Guide;
    }
  | {
      devolution: Guide;
    };

/**
 * Change-state payload. The root key must match the {guides-type} path
 * parameter ("shipping", "transport" or "devolution").
 *
 */
export type GuideStateRequest =
  | {
      shipping: GuideStateChange;
    }
  | {
      transport: GuideStateChange;
    }
  | {
      devolution: GuideStateChange;
    };

export type GuideStateChange = {
  /**
   * The new state of the guide.
   */
  state: "finalized" | "deleted" | "canceled";
  /**
   * The reason for changing the state (required for cancellation).
   */
  message?: string;
};

export type GuidesResponse = {
  guides: Array<Guide>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type Estimate = {
  id: number;
  status: string;
  archived?: boolean;
  /**
   * The estimate type (Quote, Proforma or FeesNote).
   */
  type: string;
  sequence_number?: string;
  inverted_sequence_number?: string;
  atcud?: string;
  tax_exemption?: string;
  date: string;
  due_date: string;
  reference?: string;
  observations?: string;
  retention?: string;
  permalink?: string;
  saft_hash?: string;
  sum?: number;
  discount?: number;
  before_taxes?: number;
  taxes?: number;
  total: number;
  currency?: string;
  client: Client;
  items: Array<Item>;
  global_discount?: GlobalDiscount;
};

export type EstimateBody = {
  /**
   * Document date in dd/mm/yyyy format.
   */
  date: string;
  /**
   * Expiration date in dd/mm/yyyy format.
   */
  due_date: string;
  reference?: string;
  observations?: string;
  /**
   * Retention percentage (0–99.99).
   */
  retention?: number;
  /**
   * Tax exemption code (required when an item has no tax).
   */
  tax_exemption?: string;
  tax_exemption_reason?: string;
  sequence_id?: string;
  manual_sequence_number?: string;
  currency_code?: string;
  /**
   * Exchange rate, required when currency_code differs from the account currency.
   */
  rate?: string;
  client: {
    name: string;
    code?: string;
    email?: string;
    address?: string;
    city?: string;
    postal_code?: string;
    country?: string;
    fiscal_id?: string;
    website?: string;
    phone?: string;
    fax?: string;
    observations?: string;
  };
  items: Array<Item>;
  global_discount?: GlobalDiscount;
};

/**
 * Create/update payload. The root key must match the {estimates-type} path
 * parameter: "quote" for quotes, "proforma" for proformas, "fees_note" for
 * fees_notes.
 *
 */
export type EstimateRequest =
  | {
      quote: EstimateBody;
    }
  | {
      proforma: EstimateBody;
    }
  | {
      fees_note: EstimateBody;
    };

/**
 * A single estimate, wrapped under the key matching its type
 * ("quote", "proforma" or "fees_note").
 *
 */
export type EstimateResponse =
  | {
      quote: Estimate;
    }
  | {
      proforma: Estimate;
    }
  | {
      fees_note: Estimate;
    };

/**
 * Change-state payload. The root key must match the {estimates-type} path
 * parameter ("quote", "proforma" or "fees_note").
 *
 */
export type EstimateStateRequest =
  | {
      quote: EstimateStateChange;
    }
  | {
      proforma: EstimateStateChange;
    }
  | {
      fees_note: EstimateStateChange;
    };

export type EstimateStateChange = {
  /**
   * The new state of the estimate.
   */
  state: "finalized" | "deleted" | "accepted" | "refused" | "canceled";
  /**
   * The reason for changing the state (required for cancellation).
   */
  message?: string;
};

export type EstimatesResponse = {
  estimates: Array<Estimate>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type Sequence = {
  id: number;
  /**
   * The series identifier (e.g. "2026").
   */
  serie: string;
  /**
   * Whether this is the account's current/default sequence.
   */
  default_sequence?: boolean;
  /**
   * Whether the sequence has been registered with the Tax Authority.
   */
  registered?: boolean;
  current_invoice_number?: number;
  current_invoice_receipt_number?: number;
  current_simplified_invoice_number?: number;
  current_credit_note_number?: number;
  current_debit_note_number?: number;
  current_receipt_number?: number;
  current_money_receipt_number?: number;
  current_quote_number?: number;
  current_proforma_number?: number;
  current_fees_note_number?: number;
  current_shipping_number?: number;
  current_transport_number?: number;
  current_devolution_number?: number;
};

export type SequenceBody = {
  /**
   * The series identifier (e.g. "2026").
   */
  serie: string;
  /**
   * Set to "1" to make this the account's current/default sequence.
   */
  default_sequence?: "0" | "1";
  current_invoice_number?: number;
  current_credit_note_number?: number;
  current_debit_note_number?: number;
  current_receipt_number?: number;
};

export type SequenceRequest = {
  sequence: SequenceBody;
};

export type SequenceResponse = {
  sequence: Sequence;
};

export type SequencesResponse = {
  sequences: Array<Sequence>;
};

export type Account = {
  id: number;
  organization_name?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  fiscal_id?: string;
  tax_country?: string;
  language?: string;
  /**
   * The account's InvoiceXpress URL (subdomain).
   */
  url?: string;
};

export type AccountBody = {
  first_name?: string;
  last_name?: string;
  organization_name: string;
  email: string;
  /**
   * Required when creating an account for a new user (not for create_already_user).
   */
  password?: string;
  phone?: string;
  fiscal_id?: string;
  /**
   * ISO country code (e.g. "PT").
   */
  tax_country?: string;
  /**
   * Language code (e.g. "pt").
   */
  language?: string;
  /**
   * Whether the terms of service were accepted.
   */
  terms?: "0" | "1";
  marketing?: "0" | "1";
};

export type AccountRequest = {
  account: AccountBody;
};

export type AccountResponse = {
  account: Account;
};

export type AtCommunicationRequest = {
  at_communication: {
    /**
     * The account's AT (Tax Authority) login.
     */
    login?: string;
    /**
     * The account's AT (Tax Authority) password.
     */
    password?: string;
  };
};

export type Regularization = {
  id: number;
  number?: string;
  value: number;
  date: string;
  observation?: string;
};

export type RegularizationBody = {
  /**
   * The regularization amount.
   */
  value: number;
  /**
   * Regularization date in YYYY-MM-DD format.
   */
  date: string;
  observation?: string;
};

export type RegularizationRequest = {
  regularization: RegularizationBody;
};

export type RegularizationsResponse = {
  regularization: Array<Regularization>;
  pagination?: {
    total_entries?: number;
    current_page?: number;
    total_pages?: number;
    per_page?: number;
  };
};

export type TreasuryMovement = {
  id?: number;
  value: number;
  movement_type: "Reimbursement" | "Payment";
  /**
   * Payment method code (e.g. MB, TB, CC, CD, CH).
   */
  payment_method?: string;
  date: string;
  serie?: string;
  observation?: string;
};

export type TreasuryMovementBody = {
  value: number;
  movement_type: "Reimbursement" | "Payment";
  /**
   * Payment method code (e.g. MB, TB, CC, CD, CH).
   */
  payment_method?: string;
  /**
   * Movement date in YYYY-MM-DD format.
   */
  date: string;
  serie?: string;
  observation?: string;
};

export type TreasuryMovementRequest = {
  treasury_movement: TreasuryMovementBody;
};

export type TreasuryMovementResponse = {
  treasury_movement: TreasuryMovement;
};

export type InitialBalanceRequest = {
  initial_balance: {
    /**
     * The client's initial balance amount.
     */
    value: number;
    /**
     * Balance date in YYYY-MM-DD format.
     */
    date?: string;
  };
};

export type BalanceResponse = {
  /**
   * The client's current treasury balance.
   */
  balance?: number;
  initial_balance?: number;
  currency?: string;
};

export type ErrorResponse = {
  error?: string;
};

export type PutInvoiceReceiptsByDocumentIdEmailDocumentJsonData = {
  body: {
    message?: {
      client?: {
        email?: string;
        save?: "0" | "1";
      };
      subject?: string;
      body?: string;
      cc?: string;
      bcc?: string;
      logo?: "0" | "1";
    };
  };
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/invoice_receipts/{document-id}/email-document.json";
};

export type PutInvoiceReceiptsByDocumentIdEmailDocumentJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. The supplied document-id doesn’t match any existing document.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PutInvoiceReceiptsByDocumentIdEmailDocumentJsonResponses = {
  /**
   * The email was sent successfully.
   */
  200: unknown;
};

export type PutInvoiceReceiptsByDocumentIdChangeStateJsonData = {
  body: {
    invoice_receipt: {
      /**
       * The new state of the document.
       */
      state?: "finalized" | "deleted" | "canceled" | "settled" | "unsettled";
      /**
       * The reason for changing the state (required for cancellation).
       */
      message?: string;
    };
  };
  path: {
    /**
     * The unique identifier of the document.
     */
    "document-id": number;
  };
  query: {
    /**
     * Your API key.
     */
    api_key: string;
  };
  url: "/invoice_receipts/{document-id}/change-state.json";
};

export type PutInvoiceReceiptsByDocumentIdChangeStateJsonErrors = {
  /**
   * Invalid request.
   */
  400: {
    /**
     * Status of the request.
     */
    status?: string;
  };
};

export type PutInvoiceReceiptsByDocumentIdChangeStateJsonError =
  PutInvoiceReceiptsByDocumentIdChangeStateJsonErrors[keyof PutInvoiceReceiptsByDocumentIdChangeStateJsonErrors];

export type PutInvoiceReceiptsByDocumentIdChangeStateJsonResponses = {
  /**
   * Successfully changed the document state.
   */
  200: {
    /**
     * Status of the request.
     */
    status?: string;
    /**
     * Details about the request outcome.
     */
    message?: string;
  };
};

export type PutInvoiceReceiptsByDocumentIdChangeStateJsonResponse =
  PutInvoiceReceiptsByDocumentIdChangeStateJsonResponses[keyof PutInvoiceReceiptsByDocumentIdChangeStateJsonResponses];

export type GetInvoiceReceiptsByDocumentIdJsonData = {
  body?: never;
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/invoice_receipts/{document-id}.json";
};

export type GetInvoiceReceiptsByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No invoice matches the supplied document-id.
   */
  404: unknown;
};

export type GetInvoiceReceiptsByDocumentIdJsonResponses = {
  /**
   * The invoice was returned successfully.
   */
  200: Invoice;
};

export type GetInvoiceReceiptsByDocumentIdJsonResponse =
  GetInvoiceReceiptsByDocumentIdJsonResponses[keyof GetInvoiceReceiptsByDocumentIdJsonResponses];

export type GetApiPdfByDocumentIdJsonData = {
  body?: never;
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
    second_copy?: boolean;
  };
  url: "/api/pdf/{document-id}.json";
};

export type GetApiPdfByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No document matches the supplied document-id.
   */
  404: unknown;
  /**
   * Not acceptable. The document-id provided is in an invalid state.
   */
  422: unknown;
};

export type GetApiPdfByDocumentIdJsonResponses = {
  /**
   * The request has been successfully processed.
   */
  200: unknown;
  /**
   * The request will be processed. You need to keep requesting until you get a response with HTTP status code 200.
   */
  202: unknown;
};

export type PostInvoiceReceiptsJsonData = {
  body: InvoiceReceiptsRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/invoice_receipts.json";
};

export type PostInvoiceReceiptsJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Conflict. There’s an ongoing document creation with the provided UID.
   */
  409: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostInvoiceReceiptsJsonResponses = {
  /**
   * Invoice was created successfully.
   */
  201: {
    invoice_receipt?: Invoice;
  };
};

export type PostInvoiceReceiptsJsonResponse =
  PostInvoiceReceiptsJsonResponses[keyof PostInvoiceReceiptsJsonResponses];

export type GetInvoicesJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
    text?: string;
    "type[]": Array<
      | "Invoice"
      | "InvoiceReceipt"
      | "SimplifiedInvoice"
      | "VatMossInvoice"
      | "CreditNote"
      | "DebitNote"
      | "Receipt"
      | "CashInvoice"
      | "VatMossReceipt"
      | "VatMossCreditNote"
    >;
    "status[]": Array<
      "draft" | "sent" | "settled" | "canceled" | "second_copy"
    >;
    "date[from]"?: string;
    "date[to]"?: string;
    "due_date[from]"?: string;
    "due_date[to]"?: string;
    "total_before_taxes[from]"?: number;
    "total_before_taxes[to]"?: number;
    non_archived: boolean;
    archived?: boolean;
    /**
     * Page number to retrieve.
     */
    page: number;
    /**
     * Per_page number to retrieve.
     */
    per_page: number;
    reference?: string;
  };
  url: "/invoices.json";
};

export type GetInvoicesJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
};

export type GetInvoicesJsonResponses = {
  /**
   * The client’s invoices
   */
  200: InvoicesResponse;
};

export type GetInvoicesJsonResponse =
  GetInvoicesJsonResponses[keyof GetInvoicesJsonResponses];

export type PostInvoicesJsonData = {
  body: InvoiceRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/invoices.json";
};

export type PostInvoicesJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Conflict. There’s an ongoing document creation with the provided UID.
   */
  409: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostInvoicesJsonResponses = {
  /**
   * Invoice was created successfully.
   */
  201: InvoiceResponse;
};

export type PostInvoicesJsonResponse =
  PostInvoicesJsonResponses[keyof PostInvoicesJsonResponses];

export type GetInvoicesByDocumentIdJsonData = {
  body?: never;
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/invoices/{document-id}.json";
};

export type GetInvoicesByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No invoice matches the supplied document-id.
   */
  404: unknown;
};

export type GetInvoicesByDocumentIdJsonResponses = {
  /**
   * The invoice was returned successfully.
   */
  200: InvoiceResponse;
};

export type GetInvoicesByDocumentIdJsonResponse =
  GetInvoicesByDocumentIdJsonResponses[keyof GetInvoicesByDocumentIdJsonResponses];

export type PutInvoicesByDocumentIdJsonData = {
  body: InvoiceRequest;
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/invoices/{document-id}.json";
};

export type PutInvoicesByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No invoice matches the supplied document-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PutInvoicesByDocumentIdJsonResponses = {
  /**
   * Invoice was updated successfully.
   */
  200: unknown;
};

export type PutInvoicesByDocumentIdChangeStateJsonData = {
  body: {
    invoice: {
      /**
       * The new state of the document.
       */
      state?: "finalized" | "deleted" | "canceled" | "settled";
      /**
       * The reason for changing the state (required for cancellation).
       */
      message?: string;
    };
  };
  path: {
    /**
     * The unique identifier of the document.
     */
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/invoices/{document-id}/change-state.json";
};

export type PutInvoicesByDocumentIdChangeStateJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. The supplied document-id doesn’t match any existing document.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PutInvoicesByDocumentIdChangeStateJsonResponses = {
  /**
   * Successfully changed the document state.
   */
  200: unknown;
};

export type GetDocumentByDocumentIdRelatedDocumentsJsonData = {
  body?: never;
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/document/{document-id}/related_documents.json";
};

export type GetDocumentByDocumentIdRelatedDocumentsJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No document matches the supplied document-id.
   */
  404: unknown;
};

export type GetDocumentByDocumentIdRelatedDocumentsJsonResponses = {
  /**
   * The related documents.
   */
  200: InvoicesResponse;
};

export type GetDocumentByDocumentIdRelatedDocumentsJsonResponse =
  GetDocumentByDocumentIdRelatedDocumentsJsonResponses[keyof GetDocumentByDocumentIdRelatedDocumentsJsonResponses];

export type PostDocumentsByDocumentIdPartialPaymentsJsonData = {
  body: {
    partial_payment: {
      /**
       * Payment method code (e.g. TB, MB, NU, CC).
       */
      payment_mechanism?: string;
      note?: string;
      serie?: string;
      amount?: number;
      /**
       * Payment date in dd/mm/yyyy format.
       */
      payment_date?: string;
    };
  };
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/documents/{document-id}/partial_payments.json";
};

export type PostDocumentsByDocumentIdPartialPaymentsJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No document matches the supplied document-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PostDocumentsByDocumentIdPartialPaymentsJsonResponses = {
  /**
   * The receipt was created successfully.
   */
  201: unknown;
};

export type PutReceiptsByReceiptIdChangeStateJsonData = {
  body: {
    receipt: {
      /**
       * The new state of the receipt.
       */
      state: "canceled";
      /**
       * The reason for the cancellation.
       */
      message?: string;
    };
  };
  path: {
    /**
     * The ID of the receipt to cancel.
     */
    "receipt-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/receipts/{receipt-id}/change-state.json";
};

export type PutReceiptsByReceiptIdChangeStateJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No receipt matches the supplied receipt-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PutReceiptsByReceiptIdChangeStateJsonResponses = {
  /**
   * The payment was canceled successfully.
   */
  200: unknown;
};

export type GetClientsJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
    /**
     * Page number to retrieve.
     */
    page: number;
    /**
     * Number of clients per page.
     */
    per_page: number;
  };
  url: "/clients.json";
};

export type GetClientsJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
};

export type GetClientsJsonError =
  GetClientsJsonErrors[keyof GetClientsJsonErrors];

export type GetClientsJsonResponses = {
  /**
   * Clients List all
   */
  200: ClientsResponse;
};

export type GetClientsJsonResponse =
  GetClientsJsonResponses[keyof GetClientsJsonResponses];

export type PostClientsJsonData = {
  body: ClientRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/clients.json";
};

export type PostClientsJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * UNPROCESSABLE ENTITY
   */
  422: ErrorResponse;
};

export type PostClientsJsonError =
  PostClientsJsonErrors[keyof PostClientsJsonErrors];

export type PostClientsJsonResponses = {
  /**
   * SUCCESS
   */
  201: ClientResponse;
};

export type PostClientsJsonResponse =
  PostClientsJsonResponses[keyof PostClientsJsonResponses];

export type GetClientsByClientIdJsonData = {
  body?: never;
  path: {
    /**
     * The ID of the client you want to get.
     */
    "client-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/clients/{client-id}.json";
};

export type GetClientsByClientIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type GetClientsByClientIdJsonError =
  GetClientsByClientIdJsonErrors[keyof GetClientsByClientIdJsonErrors];

export type GetClientsByClientIdJsonResponses = {
  /**
   * Clients Get
   */
  200: ClientResponse;
};

export type GetClientsByClientIdJsonResponse =
  GetClientsByClientIdJsonResponses[keyof GetClientsByClientIdJsonResponses];

export type PutClientsByClientIdJsonData = {
  body: ClientRequest;
  path: {
    /**
     * The ID of the client to be updated.
     */
    "client-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/clients/{client-id}.json";
};

export type PutClientsByClientIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
  /**
   * UNPROCESSABLE ENTITY
   */
  422: ErrorResponse;
};

export type PutClientsByClientIdJsonError =
  PutClientsByClientIdJsonErrors[keyof PutClientsByClientIdJsonErrors];

export type PutClientsByClientIdJsonResponses = {
  /**
   * SUCCESS
   */
  200: unknown;
};

export type GetClientsFindByNameJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
    client_name: string;
  };
  url: "/clients/find-by-name.json";
};

export type GetClientsFindByNameJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type GetClientsFindByNameJsonError =
  GetClientsFindByNameJsonErrors[keyof GetClientsFindByNameJsonErrors];

export type GetClientsFindByNameJsonResponses = {
  /**
   * Client Get
   */
  200: ClientResponse;
};

export type GetClientsFindByNameJsonResponse =
  GetClientsFindByNameJsonResponses[keyof GetClientsFindByNameJsonResponses];

export type GetClientsFindByCodeJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
    /**
     * The client code you want to search.
     */
    client_code: number;
  };
  url: "/clients/find-by-code.json";
};

export type GetClientsFindByCodeJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type GetClientsFindByCodeJsonError =
  GetClientsFindByCodeJsonErrors[keyof GetClientsFindByCodeJsonErrors];

export type GetClientsFindByCodeJsonResponses = {
  /**
   * Client Get
   */
  200: ClientResponse;
};

export type GetClientsFindByCodeJsonResponse =
  GetClientsFindByCodeJsonResponses[keyof GetClientsFindByCodeJsonResponses];

export type PostClientsByClientIdInvoicesJsonData = {
  body: {
    filter?: {
      status?: Array<string>;
      by_type?: Array<string>;
      archived?: Array<string>;
    };
  };
  path: {
    /**
     * Filter invoices for this client.
     */
    "client-id": number;
  };
  query: {
    api_key: string;
    /**
     * You can ask for a specific page of invoices. Defaults to 1.
     */
    page?: number;
    /**
     * You can specify how many results you want to fetch. Defaults to 10 or value defined in account settings (10, 20 or 30).
     */
    per_page?: number;
  };
  url: "/clients/{client-id}/invoices.json";
};

export type PostClientsByClientIdInvoicesJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type PostClientsByClientIdInvoicesJsonError =
  PostClientsByClientIdInvoicesJsonErrors[keyof PostClientsByClientIdInvoicesJsonErrors];

export type PostClientsByClientIdInvoicesJsonResponses = {
  /**
   * The client’s invoices
   */
  200: InvoicesResponse;
};

export type PostClientsByClientIdInvoicesJsonResponse =
  PostClientsByClientIdInvoicesJsonResponses[keyof PostClientsByClientIdInvoicesJsonResponses];

export type GetApiExportSaftJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
    month: string;
    years: string;
  };
  url: "/api/export_saft.json";
};

export type GetApiExportSaftJsonErrors = {
  /**
   * Some parameters sent in the request were not valid.
   */
  422: unknown;
  /**
   * The SAF-T file generation failed.
   */
  500: {
    message?: string;
  };
};

export type GetApiExportSaftJsonError =
  GetApiExportSaftJsonErrors[keyof GetApiExportSaftJsonErrors];

export type GetApiExportSaftJsonResponses = {
  /**
   * The link to download your SAF-T file.
   */
  200: {
    url?: string;
  };
  /**
   * Your SAF-T file is being generated. You need to keep requesting until you get a response with HTTP status code 200.
   */
  202: {
    message?: string;
  };
};

export type GetApiExportSaftJsonResponse =
  GetApiExportSaftJsonResponses[keyof GetApiExportSaftJsonResponses];

export type GetTaxesJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/taxes.json";
};

export type GetTaxesJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
};

export type GetTaxesJsonError = GetTaxesJsonErrors[keyof GetTaxesJsonErrors];

export type GetTaxesJsonResponses = {
  /**
   * Taxes List all
   */
  200: TaxesResponse;
};

export type GetTaxesJsonResponse =
  GetTaxesJsonResponses[keyof GetTaxesJsonResponses];

export type PostTaxesJsonData = {
  body: TaxRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/taxes.json";
};

export type PostTaxesJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * UNPROCESSABLE ENTITY
   */
  422: ErrorResponse;
};

export type PostTaxesJsonError = PostTaxesJsonErrors[keyof PostTaxesJsonErrors];

export type PostTaxesJsonResponses = {
  /**
   * SUCCESS
   */
  201: TaxResponse;
};

export type PostTaxesJsonResponse =
  PostTaxesJsonResponses[keyof PostTaxesJsonResponses];

export type DeleteTaxesByTaxIdJsonData = {
  body?: never;
  path: {
    /**
     * The ID of the tax to be deleted.
     */
    "tax-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/taxes/{tax-id}.json";
};

export type DeleteTaxesByTaxIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type DeleteTaxesByTaxIdJsonError =
  DeleteTaxesByTaxIdJsonErrors[keyof DeleteTaxesByTaxIdJsonErrors];

export type DeleteTaxesByTaxIdJsonResponses = {
  /**
   * SUCCESS
   */
  200: unknown;
};

export type GetTaxesByTaxIdJsonData = {
  body?: never;
  path: {
    /**
     * The ID of the tax you want to get.
     */
    "tax-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/taxes/{tax-id}.json";
};

export type GetTaxesByTaxIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type GetTaxesByTaxIdJsonError =
  GetTaxesByTaxIdJsonErrors[keyof GetTaxesByTaxIdJsonErrors];

export type GetTaxesByTaxIdJsonResponses = {
  /**
   * Tax Get
   */
  200: TaxResponse;
};

export type GetTaxesByTaxIdJsonResponse =
  GetTaxesByTaxIdJsonResponses[keyof GetTaxesByTaxIdJsonResponses];

export type PutTaxesByTaxIdJsonData = {
  body: TaxRequest;
  path: {
    /**
     * The ID of the tax to be updated.
     */
    "tax-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/taxes/{tax-id}.json";
};

export type PutTaxesByTaxIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
  /**
   * UNPROCESSABLE ENTITY
   */
  422: ErrorResponse;
};

export type PutTaxesByTaxIdJsonError =
  PutTaxesByTaxIdJsonErrors[keyof PutTaxesByTaxIdJsonErrors];

export type PutTaxesByTaxIdJsonResponses = {
  /**
   * SUCCESS
   */
  200: TaxResponse;
};

export type PutTaxesByTaxIdJsonResponse =
  PutTaxesByTaxIdJsonResponses[keyof PutTaxesByTaxIdJsonResponses];

export type GetItemsJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/items.json";
};

export type GetItemsJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
};

export type GetItemsJsonError = GetItemsJsonErrors[keyof GetItemsJsonErrors];

export type GetItemsJsonResponses = {
  /**
   * Items List all
   */
  200: ItemsResponse;
};

export type GetItemsJsonResponse =
  GetItemsJsonResponses[keyof GetItemsJsonResponses];

export type PostItemsJsonData = {
  body: ItemRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/items.json";
};

export type PostItemsJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * UNPROCESSABLE ENTITY
   */
  422: ErrorResponse;
};

export type PostItemsJsonError = PostItemsJsonErrors[keyof PostItemsJsonErrors];

export type PostItemsJsonResponses = {
  /**
   * SUCCESS
   */
  201: ItemResponse;
};

export type PostItemsJsonResponse =
  PostItemsJsonResponses[keyof PostItemsJsonResponses];

export type DeleteItemsByItemIdJsonData = {
  body?: never;
  path: {
    /**
     * The ID of the item to be deleted.
     */
    "item-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/items/{item-id}.json";
};

export type DeleteItemsByItemIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type DeleteItemsByItemIdJsonError =
  DeleteItemsByItemIdJsonErrors[keyof DeleteItemsByItemIdJsonErrors];

export type DeleteItemsByItemIdJsonResponses = {
  /**
   * SUCCESS
   */
  200: unknown;
};

export type GetItemsByItemIdJsonData = {
  body?: never;
  path: {
    /**
     * The ID of the item you want to get.
     */
    "item-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/items/{item-id}.json";
};

export type GetItemsByItemIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
};

export type GetItemsByItemIdJsonError =
  GetItemsByItemIdJsonErrors[keyof GetItemsByItemIdJsonErrors];

export type GetItemsByItemIdJsonResponses = {
  /**
   * Item Get
   */
  200: ItemResponse;
};

export type GetItemsByItemIdJsonResponse =
  GetItemsByItemIdJsonResponses[keyof GetItemsByItemIdJsonResponses];

export type PutItemsByItemIdJsonData = {
  body: ItemRequest;
  path: {
    /**
     * The ID of the item to be updated.
     */
    "item-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/items/{item-id}.json";
};

export type PutItemsByItemIdJsonErrors = {
  /**
   * ACCESS DENIED
   */
  401: ErrorResponse;
  /**
   * NOT FOUND
   */
  404: ErrorResponse;
  /**
   * UNPROCESSABLE ENTITY
   */
  422: ErrorResponse;
};

export type PutItemsByItemIdJsonError =
  PutItemsByItemIdJsonErrors[keyof PutItemsByItemIdJsonErrors];

export type PutItemsByItemIdJsonResponses = {
  /**
   * SUCCESS
   */
  200: ItemResponse;
};

export type PutItemsByItemIdJsonResponse =
  PutItemsByItemIdJsonResponses[keyof PutItemsByItemIdJsonResponses];

export type GetGuidesJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
    text?: string;
    "type[]"?: Array<"Shipping" | "Transport" | "Devolution">;
    "status[]"?: Array<"draft" | "final" | "canceled" | "second_copy">;
    "date[from]"?: string;
    "date[to]"?: string;
    non_archived?: boolean;
    archived?: boolean;
    /**
     * Page number to retrieve.
     */
    page: number;
    /**
     * Per_page number to retrieve.
     */
    per_page: number;
  };
  url: "/guides.json";
};

export type GetGuidesJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
};

export type GetGuidesJsonResponses = {
  /**
   * The list of guides.
   */
  200: GuidesResponse;
};

export type GetGuidesJsonResponse =
  GetGuidesJsonResponses[keyof GetGuidesJsonResponses];

export type GetApiQrCodesByDocumentIdJsonData = {
  body?: never;
  path: {
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/qr_codes/{document-id}.json";
};

export type GetApiQrCodesByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No document matches the supplied document-id.
   */
  404: unknown;
};

export type GetApiQrCodesByDocumentIdJsonResponses = {
  /**
   * The QR code was returned successfully.
   */
  200: unknown;
};

export type PostByGuidesTypeJsonData = {
  body: GuideRequest;
  path: {
    /**
     * The type of guide to create.
     */
    "guides-type": "shippings" | "transports" | "devolutions";
  };
  query: {
    api_key: string;
  };
  url: "/{guides-type}.json";
};

export type PostByGuidesTypeJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostByGuidesTypeJsonResponses = {
  /**
   * Guide was created successfully.
   */
  201: GuideResponse;
};

export type PostByGuidesTypeJsonResponse =
  PostByGuidesTypeJsonResponses[keyof PostByGuidesTypeJsonResponses];

export type GetByGuidesTypeByDocumentIdJsonData = {
  body?: never;
  path: {
    /**
     * The type of guide.
     */
    "guides-type": "shippings" | "transports" | "devolutions";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{guides-type}/{document-id}.json";
};

export type GetByGuidesTypeByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No guide matches the supplied document-id.
   */
  404: unknown;
};

export type GetByGuidesTypeByDocumentIdJsonResponses = {
  /**
   * The guide was returned successfully.
   */
  200: GuideResponse;
};

export type GetByGuidesTypeByDocumentIdJsonResponse =
  GetByGuidesTypeByDocumentIdJsonResponses[keyof GetByGuidesTypeByDocumentIdJsonResponses];

export type PutByGuidesTypeByDocumentIdJsonData = {
  body: GuideRequest;
  path: {
    /**
     * The type of guide.
     */
    "guides-type": "shippings" | "transports" | "devolutions";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{guides-type}/{document-id}.json";
};

export type PutByGuidesTypeByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No guide matches the supplied document-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PutByGuidesTypeByDocumentIdJsonResponses = {
  /**
   * Guide was updated successfully.
   */
  200: unknown;
};

export type PutByGuidesTypeByDocumentIdChangeStateJsonData = {
  body: GuideStateRequest;
  path: {
    /**
     * The type of guide.
     */
    "guides-type": "shippings" | "transports" | "devolutions";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{guides-type}/{document-id}/change-state.json";
};

export type PutByGuidesTypeByDocumentIdChangeStateJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. The supplied document-id doesn’t match any existing document.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PutByGuidesTypeByDocumentIdChangeStateJsonResponses = {
  /**
   * Successfully changed the guide state.
   */
  200: unknown;
};

export type PutByGuidesTypeByDocumentIdEmailDocumentJsonData = {
  body: {
    message?: {
      client?: {
        email?: string;
        save?: "0" | "1";
      };
      subject?: string;
      body?: string;
      cc?: string;
      bcc?: string;
      logo?: "0" | "1";
    };
  };
  path: {
    /**
     * The type of guide.
     */
    "guides-type": "shippings" | "transports" | "devolutions";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{guides-type}/{document-id}/email-document.json";
};

export type PutByGuidesTypeByDocumentIdEmailDocumentJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. The supplied document-id doesn’t match any existing document.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PutByGuidesTypeByDocumentIdEmailDocumentJsonResponses = {
  /**
   * The email was sent successfully.
   */
  200: unknown;
};

export type GetEstimatesJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
    text?: string;
    "type[]"?: Array<"Quote" | "Proforma" | "FeesNote">;
    "status[]"?: Array<
      | "draft"
      | "final"
      | "accepted"
      | "refused"
      | "canceled"
      | "settled"
      | "expired"
    >;
    "date[from]"?: string;
    "date[to]"?: string;
    non_archived?: boolean;
    archived?: boolean;
    /**
     * Page number to retrieve.
     */
    page: number;
    /**
     * Per_page number to retrieve.
     */
    per_page: number;
  };
  url: "/estimates.json";
};

export type GetEstimatesJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
};

export type GetEstimatesJsonResponses = {
  /**
   * The list of estimates.
   */
  200: EstimatesResponse;
};

export type GetEstimatesJsonResponse =
  GetEstimatesJsonResponses[keyof GetEstimatesJsonResponses];

export type PostByEstimatesTypeJsonData = {
  body: EstimateRequest;
  path: {
    /**
     * The type of estimate to create.
     */
    "estimates-type": "quotes" | "proformas" | "fees_notes";
  };
  query: {
    api_key: string;
  };
  url: "/{estimates-type}.json";
};

export type PostByEstimatesTypeJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostByEstimatesTypeJsonResponses = {
  /**
   * Estimate was created successfully.
   */
  201: EstimateResponse;
};

export type PostByEstimatesTypeJsonResponse =
  PostByEstimatesTypeJsonResponses[keyof PostByEstimatesTypeJsonResponses];

export type GetByEstimatesTypeByDocumentIdJsonData = {
  body?: never;
  path: {
    /**
     * The type of estimate.
     */
    "estimates-type": "quotes" | "proformas" | "fees_notes";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{estimates-type}/{document-id}.json";
};

export type GetByEstimatesTypeByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No estimate matches the supplied document-id.
   */
  404: unknown;
};

export type GetByEstimatesTypeByDocumentIdJsonResponses = {
  /**
   * The estimate was returned successfully.
   */
  200: EstimateResponse;
};

export type GetByEstimatesTypeByDocumentIdJsonResponse =
  GetByEstimatesTypeByDocumentIdJsonResponses[keyof GetByEstimatesTypeByDocumentIdJsonResponses];

export type PutByEstimatesTypeByDocumentIdJsonData = {
  body: EstimateRequest;
  path: {
    /**
     * The type of estimate.
     */
    "estimates-type": "quotes" | "proformas" | "fees_notes";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{estimates-type}/{document-id}.json";
};

export type PutByEstimatesTypeByDocumentIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No estimate matches the supplied document-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PutByEstimatesTypeByDocumentIdJsonResponses = {
  /**
   * Estimate was updated successfully.
   */
  200: unknown;
};

export type PutByEstimatesTypeByDocumentIdChangeStateJsonData = {
  body: EstimateStateRequest;
  path: {
    /**
     * The type of estimate.
     */
    "estimates-type": "quotes" | "proformas" | "fees_notes";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{estimates-type}/{document-id}/change-state.json";
};

export type PutByEstimatesTypeByDocumentIdChangeStateJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. The supplied document-id doesn’t match any existing document.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PutByEstimatesTypeByDocumentIdChangeStateJsonResponses = {
  /**
   * Successfully changed the estimate state.
   */
  200: unknown;
};

export type PutByEstimatesTypeByDocumentIdEmailDocumentJsonData = {
  body: {
    message?: {
      client?: {
        email?: string;
        save?: "0" | "1";
      };
      subject?: string;
      body?: string;
      cc?: string;
      bcc?: string;
      logo?: "0" | "1";
    };
  };
  path: {
    /**
     * The type of estimate.
     */
    "estimates-type": "quotes" | "proformas" | "fees_notes";
    "document-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/{estimates-type}/{document-id}/email-document.json";
};

export type PutByEstimatesTypeByDocumentIdEmailDocumentJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. The supplied document-id doesn’t match any existing document.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters sent were incorrect.
   */
  422: unknown;
};

export type PutByEstimatesTypeByDocumentIdEmailDocumentJsonResponses = {
  /**
   * The email was sent successfully.
   */
  200: unknown;
};

export type GetSequencesJsonData = {
  body?: never;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/sequences.json";
};

export type GetSequencesJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
};

export type GetSequencesJsonResponses = {
  /**
   * The list of sequences.
   */
  200: SequencesResponse;
};

export type GetSequencesJsonResponse =
  GetSequencesJsonResponses[keyof GetSequencesJsonResponses];

export type PostSequencesJsonData = {
  body: SequenceRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/sequences.json";
};

export type PostSequencesJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostSequencesJsonResponses = {
  /**
   * Sequence was created successfully.
   */
  201: SequenceResponse;
};

export type PostSequencesJsonResponse =
  PostSequencesJsonResponses[keyof PostSequencesJsonResponses];

export type GetSequencesBySequenceIdJsonData = {
  body?: never;
  path: {
    "sequence-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/sequences/{sequence-id}.json";
};

export type GetSequencesBySequenceIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No sequence matches the supplied sequence-id.
   */
  404: unknown;
};

export type GetSequencesBySequenceIdJsonResponses = {
  /**
   * The sequence was returned successfully.
   */
  200: SequenceResponse;
};

export type GetSequencesBySequenceIdJsonResponse =
  GetSequencesBySequenceIdJsonResponses[keyof GetSequencesBySequenceIdJsonResponses];

export type PutSequencesBySequenceIdRegisterJsonData = {
  body?: never;
  path: {
    "sequence-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/sequences/{sequence-id}/register.json";
};

export type PutSequencesBySequenceIdRegisterJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No sequence matches the supplied sequence-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PutSequencesBySequenceIdRegisterJsonResponses = {
  /**
   * The sequence was registered successfully.
   */
  200: unknown;
};

export type PutSequencesBySequenceIdSetCurrentJsonData = {
  body?: never;
  path: {
    "sequence-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/sequences/{sequence-id}/set_current.json";
};

export type PutSequencesBySequenceIdSetCurrentJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No sequence matches the supplied sequence-id.
   */
  404: unknown;
};

export type PutSequencesBySequenceIdSetCurrentJsonResponses = {
  /**
   * The current sequence was updated successfully.
   */
  200: unknown;
};

export type PostApiAccountsCreateJsonData = {
  body: AccountRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/api/accounts/create.json";
};

export type PostApiAccountsCreateJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostApiAccountsCreateJsonResponses = {
  /**
   * Account was created successfully.
   */
  201: AccountResponse;
};

export type PostApiAccountsCreateJsonResponse =
  PostApiAccountsCreateJsonResponses[keyof PostApiAccountsCreateJsonResponses];

export type PostApiAccountsCreateAlreadyUserJsonData = {
  body: AccountRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/api/accounts/create_already_user.json";
};

export type PostApiAccountsCreateAlreadyUserJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostApiAccountsCreateAlreadyUserJsonResponses = {
  /**
   * Account was created successfully.
   */
  201: AccountResponse;
};

export type PostApiAccountsCreateAlreadyUserJsonResponse =
  PostApiAccountsCreateAlreadyUserJsonResponses[keyof PostApiAccountsCreateAlreadyUserJsonResponses];

export type GetApiAccountsByAccountIdGetJsonData = {
  body?: never;
  path: {
    "account-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/accounts/{account-id}/get.json";
};

export type GetApiAccountsByAccountIdGetJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No account matches the supplied account-id.
   */
  404: unknown;
};

export type GetApiAccountsByAccountIdGetJsonResponses = {
  /**
   * The account was returned successfully.
   */
  200: AccountResponse;
};

export type GetApiAccountsByAccountIdGetJsonResponse =
  GetApiAccountsByAccountIdGetJsonResponses[keyof GetApiAccountsByAccountIdGetJsonResponses];

export type PutApiAccountsByAccountIdUpdateJsonData = {
  body: AccountRequest;
  path: {
    "account-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/accounts/{account-id}/update.json";
};

export type PutApiAccountsByAccountIdUpdateJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No account matches the supplied account-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PutApiAccountsByAccountIdUpdateJsonResponses = {
  /**
   * Account was updated successfully.
   */
  200: unknown;
};

export type PostApiV3AccountsAtCommunicationJsonData = {
  body: AtCommunicationRequest;
  path?: never;
  query: {
    api_key: string;
  };
  url: "/api/v3/accounts/at_communication.json";
};

export type PostApiV3AccountsAtCommunicationJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostApiV3AccountsAtCommunicationJsonResponses = {
  /**
   * The AT communication was submitted successfully.
   */
  200: unknown;
};

export type GetApiV3ClientsByClientIdBalanceJsonData = {
  body?: never;
  path: {
    "client-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/v3/clients/{client-id}/balance.json";
};

export type GetApiV3ClientsByClientIdBalanceJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No client matches the supplied client-id.
   */
  404: unknown;
};

export type GetApiV3ClientsByClientIdBalanceJsonResponses = {
  /**
   * The client's balance.
   */
  200: BalanceResponse;
};

export type GetApiV3ClientsByClientIdBalanceJsonResponse =
  GetApiV3ClientsByClientIdBalanceJsonResponses[keyof GetApiV3ClientsByClientIdBalanceJsonResponses];

export type PutApiV3ClientsByClientIdInitialBalanceJsonData = {
  body: InitialBalanceRequest;
  path: {
    "client-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/v3/clients/{client-id}/initial_balance.json";
};

export type PutApiV3ClientsByClientIdInitialBalanceJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No client matches the supplied client-id.
   */
  404: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PutApiV3ClientsByClientIdInitialBalanceJsonResponses = {
  /**
   * The initial balance was updated successfully.
   */
  200: unknown;
};

export type GetApiV3ClientsByClientIdRegularizationJsonData = {
  body?: never;
  path: {
    "client-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/v3/clients/{client-id}/regularization.json";
};

export type GetApiV3ClientsByClientIdRegularizationJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No client matches the supplied client-id.
   */
  404: unknown;
};

export type GetApiV3ClientsByClientIdRegularizationJsonResponses = {
  /**
   * The client's regularizations.
   */
  200: RegularizationsResponse;
};

export type GetApiV3ClientsByClientIdRegularizationJsonResponse =
  GetApiV3ClientsByClientIdRegularizationJsonResponses[keyof GetApiV3ClientsByClientIdRegularizationJsonResponses];

export type PostApiV3ClientsByClientIdRegularizationJsonData = {
  body: RegularizationRequest;
  path: {
    "client-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/v3/clients/{client-id}/regularization.json";
};

export type PostApiV3ClientsByClientIdRegularizationJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostApiV3ClientsByClientIdRegularizationJsonResponses = {
  /**
   * The regularization was created successfully.
   */
  201: RegularizationsResponse;
};

export type PostApiV3ClientsByClientIdRegularizationJsonResponse =
  PostApiV3ClientsByClientIdRegularizationJsonResponses[keyof PostApiV3ClientsByClientIdRegularizationJsonResponses];

export type DeleteApiV3ClientsByClientIdRegularizationByIdJsonData = {
  body?: never;
  path: {
    "client-id": number;
    id: number;
  };
  query: {
    api_key: string;
  };
  url: "/api/v3/clients/{client-id}/regularization/{id}.json";
};

export type DeleteApiV3ClientsByClientIdRegularizationByIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No regularization matches the supplied id.
   */
  404: unknown;
};

export type DeleteApiV3ClientsByClientIdRegularizationByIdJsonResponses = {
  /**
   * The regularization was deleted successfully.
   */
  200: unknown;
};

export type PostApiV3ClientsByClientIdTreasuryMovementsJsonData = {
  body: TreasuryMovementRequest;
  path: {
    "client-id": number;
  };
  query: {
    api_key: string;
  };
  url: "/api/v3/clients/{client-id}/treasury_movements.json";
};

export type PostApiV3ClientsByClientIdTreasuryMovementsJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Unprocessable Entity. Some parameters were incorrect.
   */
  422: unknown;
};

export type PostApiV3ClientsByClientIdTreasuryMovementsJsonResponses = {
  /**
   * The treasury movement was created successfully.
   */
  201: TreasuryMovementResponse;
};

export type PostApiV3ClientsByClientIdTreasuryMovementsJsonResponse =
  PostApiV3ClientsByClientIdTreasuryMovementsJsonResponses[keyof PostApiV3ClientsByClientIdTreasuryMovementsJsonResponses];

export type DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonData = {
  body?: never;
  path: {
    "client-id": number;
    id: number;
  };
  query: {
    api_key: string;
  };
  url: "/api/v3/clients/{client-id}/treasury_movements/{id}.json";
};

export type DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonErrors = {
  /**
   * Access denied. The API Key parameter is missing or is incorrectly entered.
   */
  401: unknown;
  /**
   * Not found. No treasury movement matches the supplied id.
   */
  404: unknown;
};

export type DeleteApiV3ClientsByClientIdTreasuryMovementsByIdJsonResponses = {
  /**
   * The treasury movement was deleted successfully.
   */
  200: unknown;
};
