// This file is auto-generated by @hey-api/openapi-ts

export type Tax = {
  id?: number;
  name: string;
  value: number;
  region?: string;
  code?: string;
  default_tax?: number;
};

export type TaxResponse = {
  tax?: Tax;
};

export type TaxesResponse = {
  taxes: Array<Tax>;
};

export type Item = {
  name: string;
  description?: string;
  unit_price: number;
  unit?: string;
  quantity: number;
  tax?: {
    id?: number;
    name?: string;
    value?: number;
  };
  discount?: number;
  subtotal?: number;
  tax_amount?: number;
  discount_amount?: number;
  total?: number;
};

export type ItemResponse = {
  item?: Item;
};

export type ItemsResponse = {
  items: Array<Item>;
};

export type MBReference = {
  entity: string;
  value: number;
  reference: string;
};

export type GlobalDiscount = {
  value_type: string;
  value: number;
};

export type Invoice = {
  id: number;
  status: string;
  archived?: boolean;
  type: string;
  sequence_number: string;
  inverted_sequence_number?: string;
  atcud?: string;
  sequence_id?: string;
  tax_exemption?: string;
  date: string;
  due_date: string;
  reference?: string;
  observations?: string;
  retention?: string;
  permalink?: string;
  saft_hash?: string;
  sum?: number;
  discount?: number;
  before_taxes?: number;
  taxes?: number;
  total: number;
  currency?: string;
  client: Client;
  items: Array<Item>;
  mb_reference?: MBReference;
  global_discount?: GlobalDiscount;
};

export type Client = {
  id: string;
  name: string;
  email?: string;
  address?: string;
  city?: string;
  postal_code?: string;
  fiscal_id?: string;
  website?: string;
  country?: string;
  phone?: string;
  fax?: string;
  preferred_contact?: {
    name?: string;
    email?: string;
    phone?: string;
  };
  observations?: string;
  open_account_link?: string;
  send_options?: string;
  payment_days?: string;
  tax_exemption_code?: string;
};

export type ClientsResponse = {
  clients: Array<Client>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type ClientResponse = {
  client?: Client;
};

export type InvoiceReceiptsRequest = {
  invoice_receipt: {
    date: string;
    due_date: string;
    status: string;
    sequence_id?: string;
    tax_exemption?: string;
    client?: {
      name: string;
    };
    items?: Array<Item>;
  };
};

export type ClientRequest = {
  client: {
    name: string;
    code?: string;
    email?: string;
    language?: string;
    address?: string;
    city?: string;
    postal_code?: string;
    country?: string;
    fiscal_id?: string;
    website?: string;
    phone?: string;
    fax?: string;
    preferred_contact?: {
      name?: string;
      email?: string;
      phone?: string;
    };
    observations?: string;
    send_options?: string;
  };
};

export type InvoicesResponse = {
  invoices: Array<Invoice>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type InvoiceResponse = {
  invoice: Invoice;
};

export type InvoiceRequest = {
  invoice: {
    /**
     * Document date in dd/mm/yyyy format.
     */
    date: string;
    /**
     * Due date in dd/mm/yyyy format.
     */
    due_date: string;
    reference?: string;
    observations?: string;
    /**
     * Retention percentage (0–99.99).
     */
    retention?: number;
    /**
     * Tax exemption code (required when an item has no tax).
     */
    tax_exemption?: string;
    tax_exemption_reason?: string;
    sequence_id?: string;
    manual_sequence_number?: string;
    currency_code?: string;
    /**
     * Exchange rate, required when currency_code differs from the account currency.
     */
    rate?: string;
    /**
     * Whether to generate a Multibanco reference for the document.
     */
    mb_reference?: boolean;
    /**
     * Source document id (e.g. when issuing a credit note).
     */
    owner_invoice_id?: number;
    client: {
      name: string;
      code?: string;
      email?: string;
      address?: string;
      city?: string;
      postal_code?: string;
      country?: string;
      fiscal_id?: string;
      website?: string;
      phone?: string;
      fax?: string;
      observations?: string;
    };
    items: Array<Item>;
    global_discount?: GlobalDiscount;
  };
  /**
   * Idempotency key to prevent duplicate document creation.
   */
  proprietary_uid?: string;
};

export type ItemRequest = {
  item: {
    name: string;
    description?: string;
    unit_price: number;
    unit?: string;
    tax?: {
      name?: string;
    };
  };
};

export type TaxRequest = {
  tax: {
    name: string;
    value: number;
    region?: string;
    code?: string;
    default_tax?: boolean;
  };
};

export type Address = {
  detail?: string;
  city?: string;
  postal_code?: string;
  country?: string;
};

export type Guide = {
  id: number;
  status: string;
  archived?: boolean;
  /**
   * The guide type (Shipping, Transport or Devolution).
   */
  type: string;
  sequence_number?: string;
  inverted_sequence_number?: string;
  atcud?: string;
  tax_exemption?: string;
  date: string;
  /**
   * Loading date and time (dd/mm/yyyy HH:MM:SS).
   */
  loaded_at?: string;
  reference?: string;
  observations?: string;
  permalink?: string;
  saft_hash?: string;
  sum?: number;
  discount?: number;
  before_taxes?: number;
  taxes?: number;
  total?: number;
  currency?: string;
  address_from?: Address;
  address_to?: Address;
  client: Client;
  items: Array<Item>;
};

export type GuideBody = {
  /**
   * Document date in dd/mm/yyyy format.
   */
  date: string;
  /**
   * Loading date and time in dd/mm/yyyy HH:MM:SS format.
   */
  loaded_at?: string;
  reference?: string;
  observations?: string;
  /**
   * Tax exemption code (required when an item has no tax).
   */
  tax_exemption?: string;
  tax_exemption_reason?: string;
  sequence_id?: string;
  manual_sequence_number?: string;
  address_from?: Address;
  address_to?: Address;
  client: {
    name: string;
    code?: string;
    email?: string;
    address?: string;
    city?: string;
    postal_code?: string;
    country?: string;
    fiscal_id?: string;
    website?: string;
    phone?: string;
    fax?: string;
    observations?: string;
  };
  items: Array<Item>;
};

/**
 * Create/update payload. The root key must match the {guides-type} path
 * parameter: "shipping" for shippings, "transport" for transports,
 * "devolution" for devolutions.
 *
 */
export type GuideRequest =
  | {
      shipping: GuideBody;
    }
  | {
      transport: GuideBody;
    }
  | {
      devolution: GuideBody;
    };

/**
 * A single guide, wrapped under the key matching its type
 * ("shipping", "transport" or "devolution").
 *
 */
export type GuideResponse =
  | {
      shipping: Guide;
    }
  | {
      transport: Guide;
    }
  | {
      devolution: Guide;
    };

/**
 * Change-state payload. The root key must match the {guides-type} path
 * parameter ("shipping", "transport" or "devolution").
 *
 */
export type GuideStateRequest =
  | {
      shipping: GuideStateChange;
    }
  | {
      transport: GuideStateChange;
    }
  | {
      devolution: GuideStateChange;
    };

export type GuideStateChange = {
  /**
   * The new state of the guide.
   */
  state: "finalized" | "deleted" | "canceled";
  /**
   * The reason for changing the state (required for cancellation).
   */
  message?: string;
};

/**
 * The new state of the guide.
 */
export type state = "finalized" | "deleted" | "canceled";

export type GuidesResponse = {
  guides: Array<Guide>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type Estimate = {
  id: number;
  status: string;
  archived?: boolean;
  /**
   * The estimate type (Quote, Proforma or FeesNote).
   */
  type: string;
  sequence_number?: string;
  inverted_sequence_number?: string;
  atcud?: string;
  tax_exemption?: string;
  date: string;
  due_date: string;
  reference?: string;
  observations?: string;
  retention?: string;
  permalink?: string;
  saft_hash?: string;
  sum?: number;
  discount?: number;
  before_taxes?: number;
  taxes?: number;
  total: number;
  currency?: string;
  client: Client;
  items: Array<Item>;
  global_discount?: GlobalDiscount;
};

export type EstimateBody = {
  /**
   * Document date in dd/mm/yyyy format.
   */
  date: string;
  /**
   * Expiration date in dd/mm/yyyy format.
   */
  due_date: string;
  reference?: string;
  observations?: string;
  /**
   * Retention percentage (0–99.99).
   */
  retention?: number;
  /**
   * Tax exemption code (required when an item has no tax).
   */
  tax_exemption?: string;
  tax_exemption_reason?: string;
  sequence_id?: string;
  manual_sequence_number?: string;
  currency_code?: string;
  /**
   * Exchange rate, required when currency_code differs from the account currency.
   */
  rate?: string;
  client: {
    name: string;
    code?: string;
    email?: string;
    address?: string;
    city?: string;
    postal_code?: string;
    country?: string;
    fiscal_id?: string;
    website?: string;
    phone?: string;
    fax?: string;
    observations?: string;
  };
  items: Array<Item>;
  global_discount?: GlobalDiscount;
};

/**
 * Create/update payload. The root key must match the {estimates-type} path
 * parameter: "quote" for quotes, "proforma" for proformas, "fees_note" for
 * fees_notes.
 *
 */
export type EstimateRequest =
  | {
      quote: EstimateBody;
    }
  | {
      proforma: EstimateBody;
    }
  | {
      fees_note: EstimateBody;
    };

/**
 * A single estimate, wrapped under the key matching its type
 * ("quote", "proforma" or "fees_note").
 *
 */
export type EstimateResponse =
  | {
      quote: Estimate;
    }
  | {
      proforma: Estimate;
    }
  | {
      fees_note: Estimate;
    };

/**
 * Change-state payload. The root key must match the {estimates-type} path
 * parameter ("quote", "proforma" or "fees_note").
 *
 */
export type EstimateStateRequest =
  | {
      quote: EstimateStateChange;
    }
  | {
      proforma: EstimateStateChange;
    }
  | {
      fees_note: EstimateStateChange;
    };

export type EstimateStateChange = {
  /**
   * The new state of the estimate.
   */
  state: "finalized" | "deleted" | "accepted" | "refused" | "canceled";
  /**
   * The reason for changing the state (required for cancellation).
   */
  message?: string;
};

/**
 * The new state of the estimate.
 */
export type state2 =
  | "finalized"
  | "deleted"
  | "accepted"
  | "refused"
  | "canceled";

export type EstimatesResponse = {
  estimates: Array<Estimate>;
  pagination: {
    total_entries: number;
    current_page: number;
    total_pages: number;
    per_page: number;
  };
};

export type ErrorResponse = {
  error?: string;
};

export type PutInvoiceReceiptsByDocumentIdEmailDocumentJsonData = {
  apiKey: string;
  documentId: number;
  requestBody: {
    message?: {
      client?: {
        email?: string;
        save?: "0" | "1";
      };
      subject?: string;
      body?: string;
      cc?: string;
      bcc?: string;
      logo?: "0" | "1";
    };
  };
};

export type PutInvoiceReceiptsByDocumentIdEmailDocumentJsonResponse = unknown;

export type PutInvoiceReceiptsByDocumentIdChangeStateJsonData = {
  /**
   * Your API key.
   */
  apiKey: string;
  /**
   * The unique identifier of the document.
   */
  documentId: number;
  requestBody: {
    invoice_receipt: {
      /**
       * The new state of the document.
       */
      state?: "finalized" | "deleted" | "canceled" | "settled" | "unsettled";
      /**
       * The reason for changing the state (required for cancellation).
       */
      message?: string;
    };
  };
};

export type PutInvoiceReceiptsByDocumentIdChangeStateJsonResponse = {
  /**
   * Status of the request.
   */
  status?: string;
  /**
   * Details about the request outcome.
   */
  message?: string;
};

export type GetInvoiceReceiptsByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
};

export type GetInvoiceReceiptsByDocumentIdJsonResponse = Invoice;

export type GetApiPdfByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
  secondCopy?: boolean;
};

export type GetApiPdfByDocumentIdJsonResponse = unknown;

export type PostInvoiceReceiptsJsonData = {
  apiKey: string;
  requestBody: InvoiceReceiptsRequest;
};

export type PostInvoiceReceiptsJsonResponse = {
  invoice_receipts?: Invoice;
};

export type GetInvoicesJsonData = {
  apiKey: string;
  archived?: boolean;
  dateFrom?: string;
  dateTo?: string;
  dueDateFrom?: string;
  dueDateTo?: string;
  nonArchived: boolean;
  /**
   * Page number to retrieve.
   */
  page: number;
  /**
   * Per_page number to retrieve.
   */
  perPage: number;
  reference?: string;
  statusArray: Array<"draft" | "sent" | "settled" | "canceled" | "second_copy">;
  text?: string;
  totalBeforeTaxesFrom?: number;
  totalBeforeTaxesTo?: number;
  typeArray: Array<
    | "Invoice"
    | "InvoiceReceipt"
    | "SimplifiedInvoice"
    | "VatMossInvoice"
    | "CreditNote"
    | "DebitNote"
    | "Receipt"
    | "CashInvoice"
    | "VatMossReceipt"
    | "VatMossCreditNote"
  >;
};

export type GetInvoicesJsonResponse = InvoicesResponse;

export type PostInvoicesJsonData = {
  apiKey: string;
  requestBody: InvoiceRequest;
};

export type PostInvoicesJsonResponse = InvoiceResponse;

export type GetInvoicesByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
};

export type GetInvoicesByDocumentIdJsonResponse = InvoiceResponse;

export type PutInvoicesByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
  requestBody: InvoiceRequest;
};

export type PutInvoicesByDocumentIdJsonResponse = unknown;

export type PutInvoicesByDocumentIdChangeStateJsonData = {
  apiKey: string;
  /**
   * The unique identifier of the document.
   */
  documentId: number;
  requestBody: {
    invoice: {
      /**
       * The new state of the document.
       */
      state?: "finalized" | "deleted" | "canceled" | "settled";
      /**
       * The reason for changing the state (required for cancellation).
       */
      message?: string;
    };
  };
};

export type PutInvoicesByDocumentIdChangeStateJsonResponse = unknown;

export type GetDocumentByDocumentIdRelatedDocumentsJsonData = {
  apiKey: string;
  documentId: number;
};

export type GetDocumentByDocumentIdRelatedDocumentsJsonResponse =
  InvoicesResponse;

export type PostDocumentsByDocumentIdPartialPaymentsJsonData = {
  apiKey: string;
  documentId: number;
  requestBody: {
    partial_payment: {
      /**
       * Payment method code (e.g. TB, MB, NU, CC).
       */
      payment_mechanism?: string;
      note?: string;
      serie?: string;
      amount?: number;
      /**
       * Payment date in dd/mm/yyyy format.
       */
      payment_date?: string;
    };
  };
};

export type PostDocumentsByDocumentIdPartialPaymentsJsonResponse = unknown;

export type GetClientsJsonData = {
  apiKey: string;
  /**
   * Page number to retrieve.
   */
  page: number;
  /**
   * Number of clients per page.
   */
  perPage: number;
};

export type GetClientsJsonResponse = ClientsResponse;

export type PostClientsJsonData = {
  apiKey: string;
  requestBody: ClientRequest;
};

export type PostClientsJsonResponse = ClientResponse;

export type GetClientsByClientIdJsonData = {
  apiKey: string;
  /**
   * The ID of the client you want to get.
   */
  clientId: number;
};

export type GetClientsByClientIdJsonResponse = ClientResponse;

export type PutClientsByClientIdJsonData = {
  apiKey: string;
  /**
   * The ID of the client to be updated.
   */
  clientId: number;
  requestBody: ClientRequest;
};

export type PutClientsByClientIdJsonResponse = unknown;

export type GetClientsFindByNameJsonData = {
  apiKey: string;
  clientName: string;
};

export type GetClientsFindByNameJsonResponse = ClientResponse;

export type GetClientsFindByCodeJsonData = {
  apiKey: string;
  /**
   * The client code you want to search.
   */
  clientCode: number;
};

export type GetClientsFindByCodeJsonResponse = ClientResponse;

export type PostClientsByClientIdInvoicesJsonData = {
  apiKey: string;
  /**
   * Filter invoices for this client.
   */
  clientId: number;
  /**
   * You can ask for a specific page of invoices. Defaults to 1.
   */
  page?: number;
  /**
   * You can specify how many results you want to fetch. Defaults to 10 or value defined in account settings (10, 20 or 30).
   */
  perPage?: number;
  requestBody: {
    filter?: {
      status?: Array<string>;
      by_type?: Array<string>;
      archived?: Array<string>;
    };
  };
};

export type PostClientsByClientIdInvoicesJsonResponse = InvoicesResponse;

export type GetApiExportSaftJsonData = {
  apiKey: string;
  month: string;
  years: string;
};

export type GetApiExportSaftJsonResponse =
  | {
      url?: string;
    }
  | {
      message?: string;
    };

export type GetTaxesJsonData = {
  apiKey: string;
};

export type GetTaxesJsonResponse = TaxesResponse;

export type PostTaxesJsonData = {
  apiKey: string;
  requestBody: TaxRequest;
};

export type PostTaxesJsonResponse = TaxResponse;

export type GetTaxesByTaxIdJsonData = {
  apiKey: string;
  /**
   * The ID of the tax you want to get.
   */
  taxId: number;
};

export type GetTaxesByTaxIdJsonResponse = TaxResponse;

export type PutTaxesByTaxIdJsonData = {
  apiKey: string;
  requestBody: TaxRequest;
  /**
   * The ID of the tax to be updated.
   */
  taxId: number;
};

export type PutTaxesByTaxIdJsonResponse = TaxResponse;

export type DeleteTaxesByTaxIdJsonData = {
  apiKey: string;
  /**
   * The ID of the tax to be deleted.
   */
  taxId: number;
};

export type DeleteTaxesByTaxIdJsonResponse = unknown;

export type GetItemsJsonData = {
  apiKey: string;
};

export type GetItemsJsonResponse = ItemsResponse;

export type PostItemsJsonData = {
  apiKey: string;
  requestBody: ItemRequest;
};

export type PostItemsJsonResponse = ItemResponse;

export type GetItemsByItemIdJsonData = {
  apiKey: string;
  /**
   * The ID of the item you want to get.
   */
  itemId: number;
};

export type GetItemsByItemIdJsonResponse = ItemResponse;

export type PutItemsByItemIdJsonData = {
  apiKey: string;
  /**
   * The ID of the item to be updated.
   */
  itemId: number;
  requestBody: ItemRequest;
};

export type PutItemsByItemIdJsonResponse = ItemResponse;

export type DeleteItemsByItemIdJsonData = {
  apiKey: string;
  /**
   * The ID of the item to be deleted.
   */
  itemId: number;
};

export type DeleteItemsByItemIdJsonResponse = unknown;

export type GetGuidesJsonData = {
  apiKey: string;
  archived?: boolean;
  dateFrom?: string;
  dateTo?: string;
  nonArchived?: boolean;
  /**
   * Page number to retrieve.
   */
  page: number;
  /**
   * Per_page number to retrieve.
   */
  perPage: number;
  statusArray?: Array<"draft" | "final" | "canceled" | "second_copy">;
  text?: string;
  typeArray?: Array<"Shipping" | "Transport" | "Devolution">;
};

export type GetGuidesJsonResponse = GuidesResponse;

export type GetApiQrCodesByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
};

export type GetApiQrCodesByDocumentIdJsonResponse = unknown;

export type PostByGuidesTypeJsonData = {
  apiKey: string;
  /**
   * The type of guide to create.
   */
  guidesType: "shippings" | "transports" | "devolutions";
  requestBody: GuideRequest;
};

export type PostByGuidesTypeJsonResponse = GuideResponse;

export type GetByGuidesTypeByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of guide.
   */
  guidesType: "shippings" | "transports" | "devolutions";
};

export type GetByGuidesTypeByDocumentIdJsonResponse = GuideResponse;

export type PutByGuidesTypeByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of guide.
   */
  guidesType: "shippings" | "transports" | "devolutions";
  requestBody: GuideRequest;
};

export type PutByGuidesTypeByDocumentIdJsonResponse = unknown;

export type PutByGuidesTypeByDocumentIdChangeStateJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of guide.
   */
  guidesType: "shippings" | "transports" | "devolutions";
  requestBody: GuideStateRequest;
};

export type PutByGuidesTypeByDocumentIdChangeStateJsonResponse = unknown;

export type PutByGuidesTypeByDocumentIdEmailDocumentJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of guide.
   */
  guidesType: "shippings" | "transports" | "devolutions";
  requestBody: {
    message?: {
      client?: {
        email?: string;
        save?: "0" | "1";
      };
      subject?: string;
      body?: string;
      cc?: string;
      bcc?: string;
      logo?: "0" | "1";
    };
  };
};

export type PutByGuidesTypeByDocumentIdEmailDocumentJsonResponse = unknown;

export type GetEstimatesJsonData = {
  apiKey: string;
  archived?: boolean;
  dateFrom?: string;
  dateTo?: string;
  nonArchived?: boolean;
  /**
   * Page number to retrieve.
   */
  page: number;
  /**
   * Per_page number to retrieve.
   */
  perPage: number;
  statusArray?: Array<
    | "draft"
    | "final"
    | "accepted"
    | "refused"
    | "canceled"
    | "settled"
    | "expired"
  >;
  text?: string;
  typeArray?: Array<"Quote" | "Proforma" | "FeesNote">;
};

export type GetEstimatesJsonResponse = EstimatesResponse;

export type PostByEstimatesTypeJsonData = {
  apiKey: string;
  /**
   * The type of estimate to create.
   */
  estimatesType: "quotes" | "proformas" | "fees_notes";
  requestBody: EstimateRequest;
};

export type PostByEstimatesTypeJsonResponse = EstimateResponse;

export type GetByEstimatesTypeByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of estimate.
   */
  estimatesType: "quotes" | "proformas" | "fees_notes";
};

export type GetByEstimatesTypeByDocumentIdJsonResponse = EstimateResponse;

export type PutByEstimatesTypeByDocumentIdJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of estimate.
   */
  estimatesType: "quotes" | "proformas" | "fees_notes";
  requestBody: EstimateRequest;
};

export type PutByEstimatesTypeByDocumentIdJsonResponse = unknown;

export type PutByEstimatesTypeByDocumentIdChangeStateJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of estimate.
   */
  estimatesType: "quotes" | "proformas" | "fees_notes";
  requestBody: EstimateStateRequest;
};

export type PutByEstimatesTypeByDocumentIdChangeStateJsonResponse = unknown;

export type PutByEstimatesTypeByDocumentIdEmailDocumentJsonData = {
  apiKey: string;
  documentId: number;
  /**
   * The type of estimate.
   */
  estimatesType: "quotes" | "proformas" | "fees_notes";
  requestBody: {
    message?: {
      client?: {
        email?: string;
        save?: "0" | "1";
      };
      subject?: string;
      body?: string;
      cc?: string;
      bcc?: string;
      logo?: "0" | "1";
    };
  };
};

export type PutByEstimatesTypeByDocumentIdEmailDocumentJsonResponse = unknown;
